module Serde.FS.STJ.Tests.StjCodeEmitterTests

open NUnit.Framework
open Serde.FS
open Serde.FS.TypeKindTypes
open Serde.FS.STJ

let private emitter = StjCodeEmitter() :> ISerdeCodeEmitter
let private resolverEmitter = StjCodeEmitter() :> ISerdeResolverEmitter

/// Helper to build a simple field TypeInfo from a type name and primitive kind.
let private mkPrimType name kind : TypeInfo =
    { Namespace = None; EnclosingModules = []; TypeName = name; Kind = Primitive kind; Attributes = [] }

/// Helper to build a SerdeFieldInfo from a name and a simple primitive type.
let private mkField name typeName kind : SerdeFieldInfo =
    { Name = name; RawName = name; Type = mkPrimType typeName kind; Attributes = SerdeAttributes.empty; Capability = Both }

/// Helper to build a SerdeFieldInfo with a full TypeInfo.
let private mkFieldWithType name (typeInfo: TypeInfo) : SerdeFieldInfo =
    { Name = name; RawName = name; Type = typeInfo; Attributes = SerdeAttributes.empty; Capability = Both }

/// Helper to build a SerdeTypeInfo for a simple record.
let private mkRecordInfo ns typeName cap (fields: SerdeFieldInfo list) : SerdeTypeInfo =
    let rawFields =
        fields |> List.map (fun f -> { Name = f.RawName; Type = f.Type; Attributes = [] } : TypeKindTypes.FieldInfo)
    {
        Raw = {
            Namespace = ns
            EnclosingModules = []
            TypeName = typeName
            Kind = Record rawFields
            Attributes = []
        }
        Capability = cap
        Attributes = SerdeAttributes.empty
        Fields = Some fields
        UnionCases = None
    }

[<Test>]
let ``Emits valid F# for simple record`` () =
    let info = mkRecordInfo (Some "MyApp") "Person" Both [
        mkField "FName" "string" String
        mkField "LName" "string" String
        mkField "Age" "int" Int32
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("module rec Serde.Generated.Person"))
    Assert.That(code, Does.Contain("module internal PersonSerdeTypeInfo"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("JsonTypeInfo<MyApp.Person>"))
    Assert.That(code, Does.Contain("JsonMetadataServices.CreateObjectInfo<MyApp.Person>"))
    Assert.That(code, Does.Contain("""writer.WriteString("FName", value.FName)"""))
    Assert.That(code, Does.Contain("""writer.WriteString("LName", value.LName)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("Age", value.Age)"""))
    Assert.That(code, Does.Contain("writer.WriteStartObject()"))
    Assert.That(code, Does.Contain("writer.WriteEndObject()"))

[<Test>]
let ``Emits WriteBoolean for bool fields`` () =
    let info = mkRecordInfo (Some "MyApp") "Config" Serialize [
        mkField "IsEnabled" "bool" Bool
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteBoolean("IsEnabled", value.IsEnabled)"""))

[<Test>]
let ``Emits WriteNumber for numeric types`` () =
    let info = mkRecordInfo (Some "MyApp") "Numbers" Serialize [
        mkField "I" "int" Int32
        mkField "I64" "int64" Int64
        mkField "F" "float" Float64
        mkField "D" "decimal" Decimal
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteNumber("I", value.I)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("I64", value.I64)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("F", value.F)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("D", value.D)"""))

[<Test>]
let ``Emits option handling for optional fields`` () =
    let optionType = {
        Namespace = None; EnclosingModules = []; TypeName = "option"
        Kind = Option (mkPrimType "string" String); Attributes = []
    }
    let info = mkRecordInfo (Some "MyApp") "Person" Serialize [
        mkFieldWithType "MiddleName" optionType
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("match value.MiddleName with"))
    Assert.That(code, Does.Contain("| Some v ->"))
    Assert.That(code, Does.Contain("| None ->"))
    Assert.That(code, Does.Contain("""writer.WriteNull("MiddleName")"""))

[<Test>]
let ``Emits auto-generated header`` () =
    let info = mkRecordInfo (Some "MyApp") "Foo" Both [
        mkField "X" "int" Int32
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.StartWith("// <auto-generated />"))

[<Test>]
let ``Emits DateTime as WriteString with ISO format`` () =
    let info = mkRecordInfo (Some "MyApp") "Event" Serialize [
        mkField "CreatedAt" "System.DateTime" DateTime
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteString("CreatedAt", value.CreatedAt.ToString("O"))"""))

[<Test>]
let ``Emits Guid as WriteString`` () =
    let info = mkRecordInfo (Some "MyApp") "Entity" Serialize [
        mkField "Id" "System.Guid" Guid
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteString("Id", value.Id.ToString())"""))

[<Test>]
let ``Full pipeline: parse then emit`` () =
    let source = """
namespace TestApp

[<Serde>]
type Person = { FName: string; LName: string; Age: int }
"""
    let types = Serde.FS.SourceGen.AstParser.parseSource "/test.fs" source
    Assert.That(types.Length, Is.EqualTo(1))

    let code = emitter.Emit(types.[0])
    Assert.That(code, Does.Contain("module rec Serde.Generated.Person"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("JsonTypeInfo<TestApp.Person>"))
    Assert.That(code, Does.Contain("""writer.WriteString("FName", value.FName)"""))
    Assert.That(code, Does.Contain("""writer.WriteString("LName", value.LName)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("Age", value.Age)"""))

[<Test>]
let ``EmitResolver produces valid resolver for multiple types`` () =
    let types = [
        mkRecordInfo (Some "MyApp") "Person" Both [
            mkField "FName" "string" String
            mkField "LName" "string" String
        ]
        mkRecordInfo (Some "MyApp") "Address" Serialize [
            mkField "Street" "string" String
        ]
    ]

    let result = resolverEmitter.EmitResolver(types)
    Assert.That(result.IsSome, Is.True)
    let code = result.Value
    Assert.That(code, Does.Contain("module Serde.Generated.SerdeStjResolver"))
    Assert.That(code, Does.Contain("open Serde.Generated.Person"))
    Assert.That(code, Does.Contain("open Serde.Generated.Address"))
    Assert.That(code, Does.Contain("SerdeStjGeneratedResolver"))
    Assert.That(code, Does.Contain("IJsonTypeInfoResolver"))
    Assert.That(code, Does.Contain("typeof<MyApp.Person>"))
    Assert.That(code, Does.Contain("typeof<MyApp.Address>"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("addressJsonTypeInfo"))
    Assert.That(code, Does.Contain("if ty = typeof<MyApp.Person>"))
    Assert.That(code, Does.Contain("elif ty = typeof<MyApp.Address>"))
    Assert.That(code, Does.Contain("else null"))
    Assert.That(code, Does.Contain("SerdeStjResolverRegistry.registerResolver"))

[<Test>]
let ``EmitResolver returns None for empty list`` () =
    let result = resolverEmitter.EmitResolver([])
    Assert.That(result.IsNone, Is.True)
