module Serde.FS.STJ.Tests.StjCodeEmitterTests

open NUnit.Framework
open Serde.FS
open Serde.FS.TypeKindTypes
open Serde.FS.STJ

let private emitter = StjCodeEmitter() :> ISerdeCodeEmitter
let private resolverEmitter = StjCodeEmitter() :> ISerdeResolverEmitter

/// Helper to build a simple field TypeInfo from a type name and primitive kind.
let private mkPrimType name kind : TypeInfo =
    { Namespace = None; EnclosingModules = []; TypeName = name; Kind = Primitive kind; Attributes = [] }

/// Helper to build a SerdeFieldInfo from a name and a simple primitive type.
let private mkField name typeName kind : SerdeFieldInfo =
    { Name = name; RawName = name; Type = mkPrimType typeName kind; Attributes = SerdeAttributes.empty; Capability = Both }

/// Helper to build a SerdeFieldInfo with a full TypeInfo.
let private mkFieldWithType name (typeInfo: TypeInfo) : SerdeFieldInfo =
    { Name = name; RawName = name; Type = typeInfo; Attributes = SerdeAttributes.empty; Capability = Both }

/// Helper to build an option TypeInfo wrapping an inner TypeInfo.
let private mkOptionType (inner: TypeInfo) : TypeInfo =
    { Namespace = None; EnclosingModules = []; TypeName = "option"; Kind = Option inner; Attributes = [] }

/// Helper to build a SerdeTypeInfo for an option type.
let private mkOptionInfo (inner: TypeInfo) : SerdeTypeInfo =
    let optType = mkOptionType inner
    {
        Raw = optType
        Capability = Both
        Attributes = SerdeAttributes.empty
        Fields = None
        UnionCases = None
    }

/// Helper to build a SerdeTypeInfo for a simple record.
let private mkRecordInfo ns typeName cap (fields: SerdeFieldInfo list) : SerdeTypeInfo =
    let rawFields =
        fields |> List.map (fun f -> { Name = f.RawName; Type = f.Type; Attributes = [] } : TypeKindTypes.FieldInfo)
    {
        Raw = {
            Namespace = ns
            EnclosingModules = []
            TypeName = typeName
            Kind = Record rawFields
            Attributes = []
        }
        Capability = cap
        Attributes = SerdeAttributes.empty
        Fields = Some fields
        UnionCases = None
    }

[<Test>]
let ``Emits valid F# for simple record`` () =
    let info = mkRecordInfo (Some "MyApp") "Person" Both [
        mkField "FName" "string" String
        mkField "LName" "string" String
        mkField "Age" "int" Int32
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("module rec Serde.Generated.Person"))
    Assert.That(code, Does.Contain("module internal PersonSerdeTypeInfo"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("JsonTypeInfo<MyApp.Person>"))
    Assert.That(code, Does.Contain("JsonMetadataServices.CreateObjectInfo<MyApp.Person>"))
    Assert.That(code, Does.Contain("""writer.WriteString("FName", value.FName)"""))
    Assert.That(code, Does.Contain("""writer.WriteString("LName", value.LName)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("Age", value.Age)"""))
    Assert.That(code, Does.Contain("writer.WriteStartObject()"))
    Assert.That(code, Does.Contain("writer.WriteEndObject()"))

[<Test>]
let ``Emits WriteBoolean for bool fields`` () =
    let info = mkRecordInfo (Some "MyApp") "Config" Serialize [
        mkField "IsEnabled" "bool" Bool
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteBoolean("IsEnabled", value.IsEnabled)"""))

[<Test>]
let ``Emits WriteNumber for numeric types`` () =
    let info = mkRecordInfo (Some "MyApp") "Numbers" Serialize [
        mkField "I" "int" Int32
        mkField "I64" "int64" Int64
        mkField "F" "float" Float64
        mkField "D" "decimal" Decimal
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteNumber("I", value.I)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("I64", value.I64)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("F", value.F)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("D", value.D)"""))

[<Test>]
let ``Emits option handling for optional fields`` () =
    let optionType = {
        Namespace = None; EnclosingModules = []; TypeName = "option"
        Kind = Option (mkPrimType "string" String); Attributes = []
    }
    let info = mkRecordInfo (Some "MyApp") "Person" Serialize [
        mkFieldWithType "MiddleName" optionType
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("match value.MiddleName with"))
    Assert.That(code, Does.Contain("| Some v ->"))
    Assert.That(code, Does.Contain("| None ->"))
    Assert.That(code, Does.Contain("""writer.WriteNull("MiddleName")"""))

[<Test>]
let ``Emits auto-generated header`` () =
    let info = mkRecordInfo (Some "MyApp") "Foo" Both [
        mkField "X" "int" Int32
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.StartWith("// <auto-generated />"))

[<Test>]
let ``Emits DateTime as WriteString with ISO format`` () =
    let info = mkRecordInfo (Some "MyApp") "Event" Serialize [
        mkField "CreatedAt" "System.DateTime" DateTime
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteString("CreatedAt", value.CreatedAt.ToString("O"))"""))

[<Test>]
let ``Emits Guid as WriteString`` () =
    let info = mkRecordInfo (Some "MyApp") "Entity" Serialize [
        mkField "Id" "System.Guid" Guid
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("""writer.WriteString("Id", value.Id.ToString())"""))

[<Test>]
let ``Full pipeline: parse then emit`` () =
    let source = """
namespace TestApp

[<Serde>]
type Person = { FName: string; LName: string; Age: int }
"""
    let types = Serde.FS.SourceGen.AstParser.parseSource "/test.fs" source
    Assert.That(types.Length, Is.EqualTo(1))

    let code = emitter.Emit(types.[0])
    Assert.That(code, Does.Contain("module rec Serde.Generated.Person"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("JsonTypeInfo<TestApp.Person>"))
    Assert.That(code, Does.Contain("""writer.WriteString("FName", value.FName)"""))
    Assert.That(code, Does.Contain("""writer.WriteString("LName", value.LName)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("Age", value.Age)"""))

[<Test>]
let ``EmitResolver produces valid resolver for multiple types`` () =
    let types = [
        mkRecordInfo (Some "MyApp") "Person" Both [
            mkField "FName" "string" String
            mkField "LName" "string" String
        ]
        mkRecordInfo (Some "MyApp") "Address" Serialize [
            mkField "Street" "string" String
        ]
    ]

    let result = resolverEmitter.EmitResolver(types)
    Assert.That(result.IsSome, Is.True)
    let code = result.Value
    Assert.That(code, Does.Contain("module Serde.Generated.SerdeStjResolver"))
    Assert.That(code, Does.Contain("open Serde.Generated.Person"))
    Assert.That(code, Does.Contain("open Serde.Generated.Address"))
    Assert.That(code, Does.Contain("SerdeStjGeneratedResolver"))
    Assert.That(code, Does.Contain("IJsonTypeInfoResolver"))
    Assert.That(code, Does.Contain("typeof<MyApp.Person>"))
    Assert.That(code, Does.Contain("typeof<MyApp.Address>"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("addressJsonTypeInfo"))
    Assert.That(code, Does.Contain("if ty = typeof<MyApp.Person>"))
    Assert.That(code, Does.Contain("elif ty = typeof<MyApp.Address>"))
    Assert.That(code, Does.Contain("else null"))
    Assert.That(code, Does.Contain("SerdeStjResolverRegistry.registerResolver"))

[<Test>]
let ``EmitResolver returns None for empty list`` () =
    let result = resolverEmitter.EmitResolver([])
    Assert.That(result.IsNone, Is.True)

[<Test>]
let ``Emits converter for option int`` () =
    let info = mkOptionInfo (mkPrimType "int" Int32)
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("IntOptionConverter"))
    Assert.That(code, Does.Contain("JsonConverter<int option>"))
    Assert.That(code, Does.Contain("CreateValueInfo"))
    Assert.That(code, Does.Contain("JsonTokenType.Null then None"))
    Assert.That(code, Does.Contain("Some(JsonSerializer.Deserialize<int>"))
    Assert.That(code, Does.Contain("writer.WriteNullValue()"))
    Assert.That(code, Does.Contain("JsonSerializer.Serialize(writer, v, options)"))

[<Test>]
let ``Emits converter for option string`` () =
    let info = mkOptionInfo (mkPrimType "string" String)
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("StringOptionConverter"))
    Assert.That(code, Does.Contain("JsonConverter<string option>"))
    Assert.That(code, Does.Not.Contain("intOptionJsonTypeInfo"), "Should not contain int references")
    Assert.That(code, Does.Contain("stringOptionJsonTypeInfo"))

[<Test>]
let ``Emits converter for option record`` () =
    let personType : TypeInfo = {
        Namespace = Some "MyApp"; EnclosingModules = []; TypeName = "Person"
        Kind = Record []; Attributes = []
    }
    let info = mkOptionInfo personType
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("PersonOptionConverter"))
    Assert.That(code, Does.Contain("JsonConverter<MyApp.Person option>"))
    Assert.That(code, Does.Contain("Deserialize<MyApp.Person>"))

[<Test>]
let ``Emits converter for nested option option int`` () =
    let innerOption = mkOptionType (mkPrimType "int" Int32)
    let info = mkOptionInfo innerOption
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("IntOptionOptionConverter"))
    Assert.That(code, Does.Contain("JsonConverter<int option option>"))
    Assert.That(code, Does.Contain("Deserialize<int option>"))

[<Test>]
let ``EmitResolver with mixed record and option types`` () =
    let recordType = mkRecordInfo (Some "MyApp") "Person" Both [
        mkField "FName" "string" String
    ]
    let optionType = mkOptionInfo (mkPrimType "string" String)
    let types = [ recordType; optionType ]

    let result = resolverEmitter.EmitResolver(types)
    Assert.That(result.IsSome, Is.True)
    let code = result.Value
    Assert.That(code, Does.Contain("typeof<MyApp.Person>"))
    Assert.That(code, Does.Contain("typeof<string option>"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("stringOptionJsonTypeInfo"))
    Assert.That(code, Does.Contain("open Serde.Generated.Person"))
    Assert.That(code, Does.Contain("open Serde.Generated.StringOption"))

[<Test>]
let ``Emits fully-qualified type for nested record field`` () =
    let addressType : TypeInfo = {
        Namespace = Some "My.App"; EnclosingModules = []; TypeName = "Address"
        Kind = Record []; Attributes = []
    }
    let info = mkRecordInfo (Some "My.App") "User" Both [
        mkField "Name" "string" String
        mkFieldWithType "Address" addressType
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("args.[1] :?> My.App.Address"), "Constructor downcast should use FQ name")
    Assert.That(code, Does.Contain("typeof<My.App.Address>"), "ParameterType should use FQ name")
    Assert.That(code, Does.Contain("CreatePropertyInfo<My.App.Address>"), "PropertyInfo should use FQ name")
    Assert.That(code, Does.Contain("JsonPropertyInfoValues<My.App.Address>"), "PropertyInfoValues should use FQ name")

[<Test>]
let ``Emits fully-qualified type for nested record from another module`` () =
    let addressType : TypeInfo = {
        Namespace = Some "Outer"; EnclosingModules = ["Inner"]; TypeName = "Address"
        Kind = Record []; Attributes = []
    }
    let info = mkRecordInfo (Some "My.App") "User" Both [
        mkFieldWithType "Address" addressType
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("args.[0] :?> Outer.Inner.Address"), "Constructor downcast should use FQ name with module")
    Assert.That(code, Does.Contain("typeof<Outer.Inner.Address>"), "ParameterType should use FQ name with module")
    Assert.That(code, Does.Contain("CreatePropertyInfo<Outer.Inner.Address>"), "PropertyInfo should use FQ name with module")

[<Test>]
let ``Emits option handling for nested record option field`` () =
    let addressType : TypeInfo = {
        Namespace = Some "My.App"; EnclosingModules = []; TypeName = "Address"
        Kind = Record []; Attributes = []
    }
    let optionType = {
        Namespace = None; EnclosingModules = []; TypeName = "option"
        Kind = Option addressType; Attributes = []
    }
    let info = mkRecordInfo (Some "My.App") "User" Both [
        mkFieldWithType "Address" optionType
    ]

    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("match value.Address with"), "Should emit option match")
    Assert.That(code, Does.Contain("| Some v ->"), "Should emit Some case")
    Assert.That(code, Does.Contain("JsonSerializer.Serialize(writer, v, options)"), "Should serialize nested record via JsonSerializer")

/// Helper to build a tuple TypeInfo from a list of element TypeInfos.
let private mkTupleType (elements: TypeInfo list) : TypeInfo =
    let fields = elements |> List.mapi (fun i ti -> { Name = sprintf "Item%d" (i+1); Type = ti; Attributes = [] } : TypeKindTypes.FieldInfo)
    { Namespace = None; EnclosingModules = []; TypeName = "tuple"; Kind = Tuple fields; Attributes = [] }

/// Helper to build a SerdeTypeInfo for a tuple type.
let private mkTupleInfo (elements: TypeInfo list) : SerdeTypeInfo =
    let tupType = mkTupleType elements
    {
        Raw = tupType
        Capability = Both
        Attributes = SerdeAttributes.empty
        Fields = None
        UnionCases = None
    }

[<Test>]
let ``Emits converter for simple int * string tuple`` () =
    let info = mkTupleInfo [ mkPrimType "int" Int32; mkPrimType "string" String ]
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("IntStringTupleConverter"))
    Assert.That(code, Does.Contain("JsonConverter<(int * string)>"))
    Assert.That(code, Does.Contain("CreateValueInfo"))
    Assert.That(code, Does.Contain("WriteStartArray"))
    Assert.That(code, Does.Contain("WriteEndArray"))
    Assert.That(code, Does.Contain("JsonSerializer.Serialize(writer, e0, options)"))
    Assert.That(code, Does.Contain("JsonSerializer.Serialize(writer, e1, options)"))
    Assert.That(code, Does.Contain("JsonSerializer.Deserialize<int>"))
    Assert.That(code, Does.Contain("JsonSerializer.Deserialize<string>"))
    Assert.That(code, Does.Contain("module rec Serde.Generated.IntStringTuple"))
    Assert.That(code, Does.Contain("intStringTupleJsonTypeInfo"))

[<Test>]
let ``Emits converter for nested tuple (int * int) * string`` () =
    let innerTuple = mkTupleType [ mkPrimType "int" Int32; mkPrimType "int" Int32 ]
    let info = mkTupleInfo [ innerTuple; mkPrimType "string" String ]
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("IntIntTupleStringTupleConverter"))
    Assert.That(code, Does.Contain("JsonSerializer.Serialize(writer, e0, options)"))
    Assert.That(code, Does.Contain("JsonSerializer.Deserialize<(int * int)>"))

[<Test>]
let ``Emits converter for tuple containing record`` () =
    let addressType : TypeInfo = {
        Namespace = Some "My.App"; EnclosingModules = []; TypeName = "Address"
        Kind = Record []; Attributes = []
    }
    let info = mkTupleInfo [ mkPrimType "int" Int32; addressType ]
    let code = emitter.Emit(info)
    Assert.That(code, Does.Contain("JsonSerializer.Deserialize<My.App.Address>"))
    Assert.That(code, Does.Contain("JsonSerializer.Serialize(writer, e1, options)"))

[<Test>]
let ``EmitResolver with mixed record option and tuple types`` () =
    let recordType = mkRecordInfo (Some "MyApp") "Person" Both [
        mkField "FName" "string" String
    ]
    let optionType = mkOptionInfo (mkPrimType "string" String)
    let tupleType = mkTupleInfo [ mkPrimType "int" Int32; mkPrimType "string" String ]
    let types = [ recordType; optionType; tupleType ]

    let result = resolverEmitter.EmitResolver(types)
    Assert.That(result.IsSome, Is.True)
    let code = result.Value
    Assert.That(code, Does.Contain("typeof<MyApp.Person>"))
    Assert.That(code, Does.Contain("typeof<string option>"))
    Assert.That(code, Does.Contain("typeof<(int * string)>"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("stringOptionJsonTypeInfo"))
    Assert.That(code, Does.Contain("intStringTupleJsonTypeInfo"))
    Assert.That(code, Does.Contain("open Serde.Generated.Person"))
    Assert.That(code, Does.Contain("open Serde.Generated.StringOption"))
    Assert.That(code, Does.Contain("open Serde.Generated.IntStringTuple"))

[<Test>]
let ``typeInfoToPascalName produces IntStringTuple`` () =
    let ti = mkTupleType [ mkPrimType "int" Int32; mkPrimType "string" String ]
    let name = TypeKindTypes.typeInfoToPascalName ti
    Assert.That(name, Is.EqualTo("IntStringTuple"))

[<Test>]
let ``typeInfoToFqFSharpType produces parenthesized tuple`` () =
    let ti = mkTupleType [ mkPrimType "int" Int32; mkPrimType "string" String ]
    let fq = TypeKindTypes.typeInfoToFqFSharpType ti
    Assert.That(fq, Is.EqualTo("(int * string)"))

[<Test>]
let ``typeInfoToFqFSharpType produces parenthesized tuple nested in option`` () =
    let ti = mkTupleType [ mkPrimType "int" Int32; mkPrimType "string" String ]
    let optTi = mkOptionType ti
    let fq = TypeKindTypes.typeInfoToFqFSharpType optTi
    Assert.That(fq, Is.EqualTo("(int * string) option"))
