module Serde.FS.SourceGen.Tests.CodeEmitterTests

open NUnit.Framework
open Serde.FS.SourceGen

[<Test>]
let ``Emits valid F# for simple record`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Person"
        Capability = Both
        Fields = [
            { Name = "FName"; FSharpType = "string" }
            { Name = "LName"; FSharpType = "string" }
            { Name = "Age"; FSharpType = "int" }
        ]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.Contain("namespace MyApp"))
    Assert.That(code, Does.Contain("module internal PersonSerdeTypeInfo"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("JsonTypeInfo<Person>"))
    Assert.That(code, Does.Contain("JsonMetadataServices.CreateObjectInfo<Person>"))
    Assert.That(code, Does.Contain("""writer.WriteString("FName", value.FName)"""))
    Assert.That(code, Does.Contain("""writer.WriteString("LName", value.LName)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("Age", value.Age)"""))
    Assert.That(code, Does.Contain("writer.WriteStartObject()"))
    Assert.That(code, Does.Contain("writer.WriteEndObject()"))

[<Test>]
let ``Emits WriteBoolean for bool fields`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Config"
        Capability = Serialize
        Fields = [
            { Name = "IsEnabled"; FSharpType = "bool" }
        ]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.Contain("""writer.WriteBoolean("IsEnabled", value.IsEnabled)"""))

[<Test>]
let ``Emits WriteNumber for numeric types`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Numbers"
        Capability = Serialize
        Fields = [
            { Name = "I"; FSharpType = "int" }
            { Name = "I64"; FSharpType = "int64" }
            { Name = "F"; FSharpType = "float" }
            { Name = "D"; FSharpType = "decimal" }
        ]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.Contain("""writer.WriteNumber("I", value.I)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("I64", value.I64)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("F", value.F)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("D", value.D)"""))

[<Test>]
let ``Emits option handling for optional fields`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Person"
        Capability = Serialize
        Fields = [
            { Name = "MiddleName"; FSharpType = "string option" }
        ]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.Contain("match value.MiddleName with"))
    Assert.That(code, Does.Contain("| Some v ->"))
    Assert.That(code, Does.Contain("| None ->"))
    Assert.That(code, Does.Contain("""writer.WriteNull("MiddleName")"""))

[<Test>]
let ``Emits auto-generated header`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Foo"
        Capability = Both
        Fields = [{ Name = "X"; FSharpType = "int" }]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.StartWith("// <auto-generated />"))

[<Test>]
let ``Emits DateTime as WriteString with ISO format`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Event"
        Capability = Serialize
        Fields = [
            { Name = "CreatedAt"; FSharpType = "System.DateTime" }
        ]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.Contain("""writer.WriteString("CreatedAt", value.CreatedAt.ToString("O"))"""))

[<Test>]
let ``Emits Guid as WriteString`` () =
    let info = {
        Namespace = "MyApp"
        TypeName = "Entity"
        Capability = Serialize
        Fields = [
            { Name = "Id"; FSharpType = "System.Guid" }
        ]
    }

    let code = CodeEmitter.emit info
    Assert.That(code, Does.Contain("""writer.WriteString("Id", value.Id.ToString())"""))

[<Test>]
let ``Full pipeline: parse then emit`` () =
    let source = """
namespace TestApp

[<Serde>]
type Person = { FName: string; LName: string; Age: int }
"""
    let types = AstParser.parseSource "/test.fs" source
    Assert.That(types.Length, Is.EqualTo(1))

    let code = CodeEmitter.emit types.[0]
    Assert.That(code, Does.Contain("namespace TestApp"))
    Assert.That(code, Does.Contain("personJsonTypeInfo"))
    Assert.That(code, Does.Contain("""writer.WriteString("FName", value.FName)"""))
    Assert.That(code, Does.Contain("""writer.WriteString("LName", value.LName)"""))
    Assert.That(code, Does.Contain("""writer.WriteNumber("Age", value.Age)"""))
