namespace Serde.FS.STJ

open System.Text
open Serde.FS

module internal StjCodeEmitterImpl =

    let writerCallForType (fieldName: string) (normalizedType: string) (valueExpr: string) (indent: string) : string =
        match normalizedType with
        | "string" ->
            sprintf "%swriter.WriteString(\"%s\", %s)" indent fieldName valueExpr
        | "int" | "int32" | "int64" | "float" | "double" | "decimal" ->
            sprintf "%swriter.WriteNumber(\"%s\", %s)" indent fieldName valueExpr
        | "bool" ->
            sprintf "%swriter.WriteBoolean(\"%s\", %s)" indent fieldName valueExpr
        | "byte[]" ->
            sprintf "%swriter.WriteBase64String(\"%s\", %s)" indent fieldName valueExpr
        | "datetime" | "system.datetime" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString(\"O\"))" indent fieldName valueExpr
        | "guid" | "system.guid" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString())" indent fieldName valueExpr
        | _ ->
            sprintf "%swriter.WritePropertyName(\"%s\")\n%sJsonSerializer.Serialize(writer, %s, options)" indent fieldName indent valueExpr

    let writerCall (fieldName: string) (rawFieldName: string) (fsharpType: string) : string =
        let normalizedType = fsharpType.Trim().ToLowerInvariant()
        let indent = "                    "

        // Check for option types: "T option" (postfix) or "option<T>" (prefix)
        let isOption, innerType =
            if normalizedType.EndsWith(" option") then
                true, fsharpType.Trim().Substring(0, fsharpType.Trim().Length - " option".Length).Trim()
            elif normalizedType.StartsWith("option<") && normalizedType.EndsWith(">") then
                true, fsharpType.Trim().Substring("option<".Length, fsharpType.Trim().Length - "option<".Length - 1).Trim()
            else
                false, fsharpType.Trim()

        if isOption then
            let innerIndent = indent + "    "
            let innerCall = writerCallForType fieldName (innerType.ToLowerInvariant()) "v" innerIndent
            sprintf "%smatch value.%s with\n%s| Some v ->\n%s\n%s| None ->\n%swriter.WriteNull(\"%s\")"
                indent rawFieldName indent innerCall indent innerIndent fieldName
        else
            writerCallForType fieldName normalizedType (sprintf "value.%s" rawFieldName) indent

    let lowerFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToLowerInvariant(s.[0])) + s.Substring(1)

    let upperFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToUpperInvariant(s.[0])) + s.Substring(1)

    let fullyQualifiedName (info: SerdeTypeInfo) : string =
        let parts =
            [ yield! info.Raw.Namespace |> Option.toList
              yield! info.Raw.EnclosingModules
              yield info.Raw.TypeName ]
        String.concat "." parts

    let emitRecord (info: SerdeTypeInfo) : string =
        let sb = StringBuilder()

        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        let fields = info.Fields |> Option.defaultValue []

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" info.Raw.TypeName
        append ""
        append "open System"
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" info.Raw.TypeName
        append ""

        let fnName = lowerFirst info.Raw.TypeName + "JsonTypeInfo"

        let fqn = fullyQualifiedName info
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqn

        appendf "        let info ="
        appendf "            JsonMetadataServices.CreateObjectInfo<%s>(" fqn
        appendf "                options,"
        appendf "                JsonObjectInfoValues<%s>(" fqn

        // ObjectWithParameterizedConstructorCreator: constructs F# record from args array
        append  "                    ObjectWithParameterizedConstructorCreator = (fun (args: obj[]) ->"
        let fieldAssignments =
            fields
            |> List.mapi (fun i field ->
                let fsharpType = TypeKindTypes.typeInfoToFSharpString field.Type
                sprintf "%s.%s = args.[%d] :?> %s" fqn field.RawName i fsharpType)
            |> String.concat "; "
        appendf "                        { %s })," fieldAssignments

        // ConstructorParameterMetadataInitializer: describes each constructor parameter
        appendf "                    ConstructorParameterMetadataInitializer = (fun _ ->"
        appendf "                        [|"
        for i, field in fields |> List.mapi (fun i x -> i, x) do
            let fsharpType = TypeKindTypes.typeInfoToFSharpString field.Type
            appendf "                            JsonParameterInfoValues(Name = \"%s\", ParameterType = typeof<%s>, Position = %d)"
                (lowerFirst field.Name) fsharpType i
        appendf "                        |]"
        appendf "                    ),"

        appendf "                    PropertyMetadataInitializer = (fun _ ->"
        appendf "                        [|"

        for field in fields do
            let fsharpType = TypeKindTypes.typeInfoToFSharpString field.Type
            appendf "                            JsonMetadataServices.CreatePropertyInfo<%s>(" fsharpType
            appendf "                                options,"
            appendf "                                JsonPropertyInfoValues<%s>(" fsharpType
            appendf "                                    IsProperty = true,"
            appendf "                                    IsPublic = true,"
            appendf "                                    DeclaringType = typeof<%s>," fqn
            appendf "                                    PropertyName = \"%s\"," field.Name
            appendf "                                    Getter = (fun (obj: obj) -> (obj :?> %s).%s)" fqn field.RawName
            appendf "                                )"
            appendf "                            )"

        appendf "                        |]"
        appendf "                    ),"
        appendf "                    SerializeHandler = (fun writer value ->"
        appendf "                    writer.WriteStartObject()"

        for field in fields do
            let fsharpType = TypeKindTypes.typeInfoToFSharpString field.Type
            let call = writerCall field.Name field.RawName fsharpType
            append call

        appendf "                    writer.WriteEndObject()"
        appendf "                )"
        appendf "            )"
        appendf "        )"
        appendf "        if Serde.FS.Serde.Debug then"
        appendf "            printfn \"[SerdeDebug] Using generated converter for %%s\" typeof<%s>.FullName" fqn
        appendf "        info"

        sb.ToString()

    let emitOption (info: SerdeTypeInfo) : string =
        let inner =
            match info.Raw.Kind with
            | TypeKindTypes.Option inner -> inner
            | _ -> failwith "emitOption called with non-Option kind"

        let pascalName = TypeKindTypes.typeInfoToPascalName info.Raw
        let fqType = TypeKindTypes.typeInfoToFqFSharpType info.Raw
        let innerFqType = TypeKindTypes.typeInfoToFqFSharpType inner
        let converterName = pascalName + "Converter"
        let fnName = lowerFirst pascalName + "JsonTypeInfo"

        let sb = StringBuilder()
        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" pascalName
        append ""
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" pascalName
        append ""
        appendf "    type internal %s() =" converterName
        appendf "        inherit JsonConverter<%s>()" fqType
        appendf "        override _.Read(reader, _typeToConvert, options) ="
        appendf "            if reader.TokenType = JsonTokenType.Null then None"
        appendf "            else Some(JsonSerializer.Deserialize<%s>(&reader, options))" innerFqType
        appendf "        override _.Write(writer, value, options) ="
        appendf "            match value with"
        appendf "            | None -> writer.WriteNullValue()"
        appendf "            | Some v -> JsonSerializer.Serialize(writer, v, options)"
        append ""
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqType
        appendf "        JsonMetadataServices.CreateValueInfo<%s>(options, %s())" fqType converterName

        sb.ToString()

    let emit (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeKindTypes.Option _ -> emitOption info
        | _ -> emitRecord info

    let private resolverModuleName (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeKindTypes.Option _ -> TypeKindTypes.typeInfoToPascalName info.Raw
        | _ -> info.Raw.TypeName

    let private resolverFqn (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeKindTypes.Option _ -> TypeKindTypes.typeInfoToFqFSharpType info.Raw
        | _ -> fullyQualifiedName info

    let private resolverFnName (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeKindTypes.Option _ -> lowerFirst (TypeKindTypes.typeInfoToPascalName info.Raw) + "JsonTypeInfo"
        | _ -> lowerFirst info.Raw.TypeName + "JsonTypeInfo"

    let emitResolver (types: SerdeTypeInfo list) : string option =
        match types with
        | [] -> None
        | _ ->
            let sb = StringBuilder()
            let append (s: string) = sb.AppendLine(s) |> ignore
            let appendf fmt = Printf.kprintf append fmt

            append "// <auto-generated />"
            append "module Serde.Generated.SerdeStjResolver"
            append ""
            append "open System.Text.Json"
            append "open System.Text.Json.Serialization.Metadata"

            for info in types do
                appendf "open Serde.Generated.%s" (resolverModuleName info)

            append ""
            append "type internal SerdeStjGeneratedResolver() ="
            append "    interface IJsonTypeInfoResolver with"
            append "        member _.GetTypeInfo(ty, options) ="

            for i, info in types |> List.mapi (fun i x -> i, x) do
                let fqn = resolverFqn info
                let fnName = resolverFnName info
                let keyword = if i = 0 then "if" else "elif"
                appendf "            %s ty = typeof<%s> then %s options :> JsonTypeInfo" keyword fqn fnName

            append "            else null"
            append ""
            append "do Serde.FS.STJ.SerdeStjResolverRegistry.registerResolver(SerdeStjGeneratedResolver())"

            Some (sb.ToString())

type StjCodeEmitter() =
    interface ISerdeCodeEmitter with
        member _.Emit(info) = StjCodeEmitterImpl.emit info
    interface ISerdeResolverEmitter with
        member _.EmitResolver(types) = StjCodeEmitterImpl.emitResolver types
