namespace Serde.FS.STJ

open System.Text
open Serde.FS

module internal StjCodeEmitterImpl =

    let writerCallForType (fieldName: string) (normalizedType: string) (valueExpr: string) (indent: string) : string =
        match normalizedType with
        | "string" ->
            sprintf "%swriter.WriteString(\"%s\", %s)" indent fieldName valueExpr
        | "int" | "int32" | "int64" | "float" | "double" | "decimal" ->
            sprintf "%swriter.WriteNumber(\"%s\", %s)" indent fieldName valueExpr
        | "bool" ->
            sprintf "%swriter.WriteBoolean(\"%s\", %s)" indent fieldName valueExpr
        | "byte[]" ->
            sprintf "%swriter.WriteBase64String(\"%s\", %s)" indent fieldName valueExpr
        | "datetime" | "system.datetime" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString(\"O\"))" indent fieldName valueExpr
        | "guid" | "system.guid" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString())" indent fieldName valueExpr
        | _ ->
            sprintf "%swriter.WritePropertyName(\"%s\")\n%sJsonSerializer.Serialize(writer, %s, options)" indent fieldName indent valueExpr

    let writerCall (fieldName: string) (fsharpType: string) : string =
        let normalizedType = fsharpType.Trim().ToLowerInvariant()
        let indent = "                    "

        // Check for option types: "T option" (postfix) or "option<T>" (prefix)
        let isOption, innerType =
            if normalizedType.EndsWith(" option") then
                true, fsharpType.Trim().Substring(0, fsharpType.Trim().Length - " option".Length).Trim()
            elif normalizedType.StartsWith("option<") && normalizedType.EndsWith(">") then
                true, fsharpType.Trim().Substring("option<".Length, fsharpType.Trim().Length - "option<".Length - 1).Trim()
            else
                false, fsharpType.Trim()

        if isOption then
            let innerIndent = indent + "    "
            let innerCall = writerCallForType fieldName (innerType.ToLowerInvariant()) "v" innerIndent
            sprintf "%smatch value.%s with\n%s| Some v ->\n%s\n%s| None ->\n%swriter.WriteNull(\"%s\")"
                indent fieldName indent innerCall indent innerIndent fieldName
        else
            writerCallForType fieldName normalizedType (sprintf "value.%s" fieldName) indent

    let lowerFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToLowerInvariant(s.[0])) + s.Substring(1)

    let fullyQualifiedName (info: SerdeTypeInfo) : string =
        let parts =
            [ yield! info.Namespace |> Option.toList
              yield! info.EnclosingModules
              yield info.TypeName ]
        String.concat "." parts

    let emit (info: SerdeTypeInfo) : string =
        let sb = StringBuilder()

        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" info.TypeName
        append ""
        append "open System"
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" info.TypeName
        append ""

        let fnName = lowerFirst info.TypeName + "JsonTypeInfo"

        let fqn = fullyQualifiedName info
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqn

        appendf "        let info ="
        appendf "            JsonMetadataServices.CreateObjectInfo<%s>(" fqn
        appendf "                options,"
        appendf "                JsonObjectInfoValues<%s>(" fqn

        // ObjectWithParameterizedConstructorCreator: constructs F# record from args array
        append  "                    ObjectWithParameterizedConstructorCreator = (fun (args: obj[]) ->"
        let fieldAssignments =
            info.Fields
            |> List.mapi (fun i field ->
                sprintf "%s.%s = args.[%d] :?> %s" fqn field.Name i field.FSharpType)
            |> String.concat "; "
        appendf "                        { %s })," fieldAssignments

        // ConstructorParameterMetadataInitializer: describes each constructor parameter
        appendf "                    ConstructorParameterMetadataInitializer = (fun _ ->"
        appendf "                        [|"
        for i, field in info.Fields |> List.mapi (fun i x -> i, x) do
            appendf "                            JsonParameterInfoValues(Name = \"%s\", ParameterType = typeof<%s>, Position = %d)"
                (lowerFirst field.Name) field.FSharpType i
        appendf "                        |]"
        appendf "                    ),"

        appendf "                    PropertyMetadataInitializer = (fun _ ->"
        appendf "                        [|"

        for field in info.Fields do
            appendf "                            JsonMetadataServices.CreatePropertyInfo<%s>(" field.FSharpType
            appendf "                                options,"
            appendf "                                JsonPropertyInfoValues<%s>(" field.FSharpType
            appendf "                                    IsProperty = true,"
            appendf "                                    IsPublic = true,"
            appendf "                                    DeclaringType = typeof<%s>," fqn
            appendf "                                    PropertyName = \"%s\"," field.Name
            appendf "                                    Getter = (fun (obj: obj) -> (obj :?> %s).%s)" fqn field.Name
            appendf "                                )"
            appendf "                            )"

        appendf "                        |]"
        appendf "                    ),"
        appendf "                    SerializeHandler = (fun writer value ->"
        appendf "                    writer.WriteStartObject()"

        for field in info.Fields do
            let call = writerCall field.Name field.FSharpType
            append call

        appendf "                    writer.WriteEndObject()"
        appendf "                )"
        appendf "            )"
        appendf "        )"
        appendf "        if Serde.FS.Serde.Debug then"
        appendf "            printfn \"[SerdeDebug] Using generated converter for %%s\" typeof<%s>.FullName" fqn
        appendf "        info"

        sb.ToString()

    let emitResolver (types: SerdeTypeInfo list) : string option =
        match types with
        | [] -> None
        | _ ->
            let sb = StringBuilder()
            let append (s: string) = sb.AppendLine(s) |> ignore
            let appendf fmt = Printf.kprintf append fmt

            append "// <auto-generated />"
            append "module Serde.Generated.SerdeStjResolver"
            append ""
            append "open System.Text.Json"
            append "open System.Text.Json.Serialization.Metadata"

            for info in types do
                appendf "open Serde.Generated.%s" info.TypeName

            append ""
            append "type internal SerdeStjGeneratedResolver() ="
            append "    interface IJsonTypeInfoResolver with"
            append "        member _.GetTypeInfo(ty, options) ="

            for i, info in types |> List.mapi (fun i x -> i, x) do
                let fqn = fullyQualifiedName info
                let fnName = lowerFirst info.TypeName + "JsonTypeInfo"
                let keyword = if i = 0 then "if" else "elif"
                appendf "            %s ty = typeof<%s> then %s options :> JsonTypeInfo" keyword fqn fnName

            append "            else null"
            append ""
            append "do Serde.FS.STJ.SerdeStjResolverRegistry.registerResolver(SerdeStjGeneratedResolver())"

            Some (sb.ToString())

type StjCodeEmitter() =
    interface ISerdeCodeEmitter with
        member _.Emit(info) = StjCodeEmitterImpl.emit info
    interface ISerdeResolverEmitter with
        member _.EmitResolver(types) = StjCodeEmitterImpl.emitResolver types
