namespace Serde.FS.SourceGen

open System.Text

module CodeEmitter =

    let private writerCallForType (fieldName: string) (normalizedType: string) (valueExpr: string) (indent: string) : string =
        match normalizedType with
        | "string" ->
            sprintf "%swriter.WriteString(\"%s\", %s)" indent fieldName valueExpr
        | "int" | "int32" | "int64" | "float" | "double" | "decimal" ->
            sprintf "%swriter.WriteNumber(\"%s\", %s)" indent fieldName valueExpr
        | "bool" ->
            sprintf "%swriter.WriteBoolean(\"%s\", %s)" indent fieldName valueExpr
        | "byte[]" ->
            sprintf "%swriter.WriteBase64String(\"%s\", %s)" indent fieldName valueExpr
        | "datetime" | "system.datetime" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString(\"O\"))" indent fieldName valueExpr
        | "guid" | "system.guid" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString())" indent fieldName valueExpr
        | _ ->
            sprintf "%swriter.WritePropertyName(\"%s\")\n%sJsonSerializer.Serialize(writer, %s, options)" indent fieldName indent valueExpr

    let private writerCall (fieldName: string) (fsharpType: string) : string =
        let normalizedType = fsharpType.Trim().ToLowerInvariant()
        let indent = "                    "

        // Check for option types: "T option" (postfix) or "option<T>" (prefix)
        let isOption, innerType =
            if normalizedType.EndsWith(" option") then
                true, fsharpType.Trim().Substring(0, fsharpType.Trim().Length - " option".Length).Trim()
            elif normalizedType.StartsWith("option<") && normalizedType.EndsWith(">") then
                true, fsharpType.Trim().Substring("option<".Length, fsharpType.Trim().Length - "option<".Length - 1).Trim()
            else
                false, fsharpType.Trim()

        if isOption then
            let innerIndent = indent + "    "
            let innerCall = writerCallForType fieldName (innerType.ToLowerInvariant()) "v" innerIndent
            sprintf "%smatch value.%s with\n%s| Some v ->\n%s\n%s| None ->\n%swriter.WriteNull(\"%s\")"
                indent fieldName indent innerCall indent innerIndent fieldName
        else
            writerCallForType fieldName normalizedType (sprintf "value.%s" fieldName) indent

    let private lowerFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToLowerInvariant(s.[0])) + s.Substring(1)

    /// Generate F# source code for a single Serde-annotated type.
    let emit (info: SerdeTypeInfo) : string =
        let sb = StringBuilder()

        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "namespace %s" info.Namespace
        append ""
        append "open System"
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" info.TypeName
        append ""

        let fnName = lowerFirst info.TypeName + "JsonTypeInfo"

        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName info.TypeName

        appendf "        let info ="
        appendf "            JsonMetadataServices.CreateObjectInfo<%s>(" info.TypeName
        appendf "                options,"
        appendf "                JsonObjectInfoValues<%s>(" info.TypeName
        appendf "                    ObjectCreator = (fun () -> Unchecked.defaultof<%s> :> obj)," info.TypeName
        appendf "                    SerializeHandler = (fun writer value ->"
        appendf "                    writer.WriteStartObject()"

        for field in info.Fields do
            let call = writerCall field.Name field.FSharpType
            append call

        appendf "                    writer.WriteEndObject()"
        appendf "                )"
        appendf "            )"
        appendf "        )"
        appendf "        info"

        sb.ToString()
