// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IOrderApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private ProductCodec =
        let encode (value: Domain.Catalog.Product) : obj =
            createObj [
                "Id", box (value.Id)
                "Name", box (value.Name)
                "Price", box (float (value.Price))
            ]
        let decode (json: obj) : Domain.Catalog.Product =
            {
                Id = (unbox<int> (json?("Id")))
                Name = (unbox<string> (json?("Name")))
                Price = (decimal (unbox<float> (json?("Price"))))
            }

    module private OrderCodec =
        let encode (value: Domain.Shop.Order) : obj =
            createObj [
                "OrderId", box (value.OrderId)
                "Item", ProductCodec.encode (value.Item)
            ]
        let decode (json: obj) : Domain.Shop.Order =
            {
                OrderId = (unbox<int> (json?("OrderId")))
                Item = (ProductCodec.decode (json?("Item")))
            }

    let create (baseUrl: string) : Domain.Shop.IOrderApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IOrderApi/" + methodName
        { new Domain.Shop.IOrderApi with
            member _.PlaceOrder(arg: Domain.Shop.Order) =
                async {
                    let url = fullUrl "PlaceOrder"
                    let body = Interop.stringify (OrderCodec.encode (arg))
                    let! respText = Interop.postJson url body |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (unbox<int> json)
                }
        }

