// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IStatusApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private StatusCodec =
        let encode (value: Domain.Status) : obj =
            if value = Domain.Status.Pending then box "Pending"
            elif value = Domain.Status.Active then box "Active"
            elif value = Domain.Status.Closed then box "Closed"
            else failwith (sprintf "Unknown enum value: %A" value)
        let decode (json: obj) : Domain.Status =
            let s = unbox<string> json
            if s = "Pending" then Domain.Status.Pending
            elif s = "Active" then Domain.Status.Active
            elif s = "Closed" then Domain.Status.Closed
            else failwith (sprintf "Unknown enum value: %s" s)

    let create (baseUrl: string) : Domain.IStatusApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IStatusApi/" + methodName
        { new Domain.IStatusApi with
            member _.GetStatus() =
                async {
                    let url = fullUrl "GetStatus"
                    let! respText = Interop.postJson url "null" |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (StatusCodec.decode json)
                }
        }

