// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IShapeApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private ShapeCodec =
        let encode (value: Domain.Shape) : obj =
            match value with
            | Domain.Shape.Circle(e0) ->
                createObj [ "Case", box "Circle"; "Fields", box [| box (e0) |] ]
            | Domain.Shape.Rectangle(e0, e1) ->
                createObj [ "Case", box "Rectangle"; "Fields", box [| box (e0); box (e1) |] ]
            | Domain.Shape.Point -> createObj [ "Case", box "Point"; "Fields", box [||] ]

        let decode (json: obj) : Domain.Shape =
            let caseName = unbox<string> (json?Case)
            let fieldsArr = unbox<obj[]> (json?Fields)
            if caseName = "Circle" then Domain.Shape.Circle((unbox<float> (fieldsArr.[0])))
            elif caseName = "Rectangle" then Domain.Shape.Rectangle((unbox<float> (fieldsArr.[0])), (unbox<float> (fieldsArr.[1])))
            elif caseName = "Point" then Domain.Shape.Point
            else failwith (sprintf "Unknown union case: %s" caseName)

    let create (baseUrl: string) : Domain.IShapeApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IShapeApi/" + methodName
        { new Domain.IShapeApi with
            member _.GetShape(arg: int) =
                async {
                    let url = fullUrl "GetShape"
                    let body = Interop.stringify (box (arg))
                    let! respText = Interop.postJson url body |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (ShapeCodec.decode json)
                }
        }

