// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec ICartApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private CartCodec =
        let encode (value: Domain.Cart) : obj =
            createObj [
                "Id", box (value.Id)
                "Items", (value.Items |> Seq.map (fun x -> box (x)) |> Array.ofSeq |> box)
            ]
        let decode (json: obj) : Domain.Cart =
            {
                Id = (unbox<int> (json?("Id")))
                Items = (unbox<obj[]> (json?("Items")) |> Array.map (fun x -> (unbox<string> x)) |> Array.toList)
            }

    let create (baseUrl: string) : Domain.ICartApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/ICartApi/" + methodName
        { new Domain.ICartApi with
            member _.GetCart() =
                async {
                    let url = fullUrl "GetCart"
                    let! respText = Interop.postJson url "null" |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (CartCodec.decode json)
                }
        }

