// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IOrderApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private ProductCodec =
        let encode (value: Domain.Api.Product) : obj =
            createObj [
                "Id", box (value.Id)
                "Name", box (value.Name)
            ]
        let decode (json: obj) : Domain.Api.Product =
            {
                Id = (unbox<int> (json?("Id")))
                Name = (unbox<string> (json?("Name")))
            }

    let create (baseUrl: string) : Domain.Api.IOrderApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IOrderApi/" + methodName
        { new Domain.Api.IOrderApi with
            member _.GetProduct(arg: int) =
                async {
                    let url = fullUrl "GetProduct"
                    let body = Interop.stringify (box (arg))
                    let! respText = Interop.postJson url body |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (ProductCodec.decode json)
                }
        }

