// <auto-generated />
namespace Domain

open Fable.Core
open Fable.Core.JsInterop

module rec ICacheApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private CacheCodec =
        let encode (value: Domain.Cache) : obj =
            createObj [
                "Tags", (value.Tags |> Seq.map (fun x -> box (x)) |> Array.ofSeq |> box)
            ]
        let decode (json: obj) : Domain.Cache =
            {
                Tags = (unbox<obj[]> (json?("Tags")) |> Array.map (fun x -> (unbox<string> x)) :> seq<_>)
            }

    let create (baseUrl: string) : Domain.ICacheApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/ICacheApi/" + methodName
        { new Domain.ICacheApi with
            member _.GetCache() =
                async {
                    let url = fullUrl "GetCache"
                    let! respText = Interop.postJson url "null" |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (CacheCodec.decode json)
                }
        }

