// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IExportApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private ExportCodec =
        let encode (value: Domain.Export) : obj =
            createObj [
                "Payload", (box (System.Convert.ToBase64String (value.Payload)))
            ]
        let decode (json: obj) : Domain.Export =
            {
                Payload = (System.Convert.FromBase64String (unbox<string> (json?("Payload"))))
            }

    let create (baseUrl: string) : Domain.IExportApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IExportApi/" + methodName
        { new Domain.IExportApi with
            member _.Download() =
                async {
                    let url = fullUrl "Download"
                    let! respText = Interop.postJson url "null" |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (ExportCodec.decode json)
                }
        }

