// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IUserApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private UserCodec =
        let encode (value: Domain.User) : obj =
            createObj [
                "Id", box (value.Id)
                "Email", (match value.Email with | Some x -> box (x) | None -> null)
            ]
        let decode (json: obj) : Domain.User =
            {
                Id = (unbox<int> (json?("Id")))
                Email = (let v = (json?("Email")) in if Interop.isNullish v then None else Some ((unbox<string> v)))
            }

    let create (baseUrl: string) : Domain.IUserApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IUserApi/" + methodName
        { new Domain.IUserApi with
            member _.GetUser(arg: int) =
                async {
                    let url = fullUrl "GetUser"
                    let body = Interop.stringify (box (arg))
                    let! respText = Interop.postJson url body |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (UserCodec.decode json)
                }
        }

