// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec ITagCountsApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private TagCountsCodec =
        let encode (value: Domain.TagCounts) : obj =
            createObj [
                "Counts", (value.Counts |> Map.toSeq |> Seq.map (fun (k, v) -> box [| box (k); box (v) |]) |> Array.ofSeq |> box)
            ]
        let decode (json: obj) : Domain.TagCounts =
            {
                Counts = (unbox<obj[]> (json?("Counts")) |> Array.map (fun pair -> let p = unbox<obj[]> pair in ((unbox<string> p.[0]), (unbox<int> p.[1]))) |> Map.ofArray)
            }

    let create (baseUrl: string) : Domain.ITagCountsApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/ITagCountsApi/" + methodName
        { new Domain.ITagCountsApi with
            member _.GetTagCounts() =
                async {
                    let url = fullUrl "GetTagCounts"
                    let! respText = Interop.postJson url "null" |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (TagCountsCodec.decode json)
                }
        }

