// <auto-generated />
namespace SerdeGenerated.Fable

open Fable.Core
open Fable.Core.JsInterop

module rec IProductApiFableClient =

    module private Interop =
        [<Emit("JSON.stringify($0)")>]
        let stringify (x: obj) : string = jsNative

        [<Emit("JSON.parse($0)")>]
        let parse (s: string) : obj = jsNative

        [<Emit("$0 == null")>]
        let isNullish (x: obj) : bool = jsNative

        [<Emit("Object.prototype.hasOwnProperty.call($0, $1)")>]
        let hasKey (x: obj) (k: string) : bool = jsNative

        [<Emit("fetch($0, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: $1 }).then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status + ' at ' + $0); } return r.text(); })")>]
        let postJson (url: string) (body: string) : JS.Promise<string> = jsNative

    module private ProductIdCodec =
        let encode (value: Domain.ProductId) : obj =
            match value with
            | Domain.ProductId.ProductId x ->
                createObj [ "ProductId", box (x) ]
        let decode (json: obj) : Domain.ProductId =
            let v = json?("ProductId")
            Domain.ProductId.ProductId ((unbox<int> v))

    let create (baseUrl: string) : Domain.IProductApi =
        let trimmed = baseUrl.TrimEnd('/')
        let fullUrl (methodName: string) =
            trimmed + "/rpc/IProductApi/" + methodName
        { new Domain.IProductApi with
            member _.Lookup(arg: Domain.ProductId) =
                async {
                    let url = fullUrl "Lookup"
                    let body = Interop.stringify (ProductIdCodec.encode (arg))
                    let! respText = Interop.postJson url body |> Async.AwaitPromise
                    let json = Interop.parse respText
                    return (unbox<string> json)
                }
        }

