namespace Serde.FS.SystemTextJson

open System.Text
open Serde.FS
open FSharp.SourceDjinn

module internal StjCodeEmitterImpl =

    let writerCallForType (fieldName: string) (normalizedType: string) (valueExpr: string) (indent: string) : string =
        match normalizedType with
        | "string" ->
            sprintf "%swriter.WriteString(\"%s\", %s)" indent fieldName valueExpr
        | "int" | "int32" | "int64" | "float" | "double" | "decimal" ->
            sprintf "%swriter.WriteNumber(\"%s\", %s)" indent fieldName valueExpr
        | "bool" ->
            sprintf "%swriter.WriteBoolean(\"%s\", %s)" indent fieldName valueExpr
        | "byte[]" ->
            sprintf "%swriter.WriteBase64String(\"%s\", %s)" indent fieldName valueExpr
        | "datetime" | "system.datetime" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString(\"O\"))" indent fieldName valueExpr
        | "guid" | "system.guid" ->
            sprintf "%swriter.WriteString(\"%s\", %s.ToString())" indent fieldName valueExpr
        | _ ->
            sprintf "%swriter.WritePropertyName(\"%s\")\n%sJsonSerializer.Serialize(writer, %s, options)" indent fieldName indent valueExpr

    let writerCall (fieldName: string) (rawFieldName: string) (fsharpType: string) : string =
        let normalizedType = fsharpType.Trim().ToLowerInvariant()
        let indent = "                    "

        // Check for option types: "T option" (postfix) or "option<T>" (prefix)
        let isOption, innerType =
            if normalizedType.EndsWith(" option") then
                true, fsharpType.Trim().Substring(0, fsharpType.Trim().Length - " option".Length).Trim()
            elif normalizedType.StartsWith("option<") && normalizedType.EndsWith(">") then
                true, fsharpType.Trim().Substring("option<".Length, fsharpType.Trim().Length - "option<".Length - 1).Trim()
            else
                false, fsharpType.Trim()

        if isOption then
            let innerIndent = indent + "    "
            let innerCall = writerCallForType fieldName (innerType.ToLowerInvariant()) "v" innerIndent
            sprintf "%smatch value.%s with\n%s| Some v ->\n%s\n%s| None ->\n%swriter.WriteNull(\"%s\")"
                indent rawFieldName indent innerCall indent innerIndent fieldName
        else
            writerCallForType fieldName normalizedType (sprintf "value.%s" rawFieldName) indent

    let lowerFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToLowerInvariant(s.[0])) + s.Substring(1)

    let upperFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToUpperInvariant(s.[0])) + s.Substring(1)

    let fullyQualifiedName (info: SerdeTypeInfo) : string =
        let parts =
            [ yield! info.Raw.Namespace |> Option.toList
              yield! info.Raw.EnclosingModules
              yield info.Raw.TypeName ]
        String.concat "." parts

    let emitRecord (info: SerdeTypeInfo) : string =
        let sb = StringBuilder()

        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        let fields = info.Fields |> Option.defaultValue []

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" info.Raw.TypeName
        append ""
        append "open System"
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" info.Raw.TypeName
        append ""

        let fnName = lowerFirst info.Raw.TypeName + "JsonTypeInfo"

        let fqn = fullyQualifiedName info
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqn

        appendf "        let info ="
        appendf "            JsonMetadataServices.CreateObjectInfo<%s>(" fqn
        appendf "                options,"
        appendf "                JsonObjectInfoValues<%s>(" fqn

        // ObjectWithParameterizedConstructorCreator: constructs F# record from args array
        append  "                    ObjectWithParameterizedConstructorCreator = (fun (args: obj[]) ->"
        let fieldAssignments =
            fields
            |> List.mapi (fun i field ->
                let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
                sprintf "%s = args.[%d] :?> %s" field.RawName i fsharpType)
            |> String.concat "; "
        appendf "                        { %s } : %s)," fieldAssignments fqn

        // ConstructorParameterMetadataInitializer: describes each constructor parameter
        appendf "                    ConstructorParameterMetadataInitializer = (fun _ ->"
        appendf "                        [|"
        for i, field in fields |> List.mapi (fun i x -> i, x) do
            let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
            appendf "                            JsonParameterInfoValues(Name = \"%s\", ParameterType = typeof<%s>, Position = %d)"
                (lowerFirst field.Name) fsharpType i
        appendf "                        |]"
        appendf "                    ),"

        appendf "                    PropertyMetadataInitializer = (fun _ ->"
        appendf "                        [|"

        for field in fields do
            let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
            appendf "                            JsonMetadataServices.CreatePropertyInfo<%s>(" fsharpType
            appendf "                                options,"
            appendf "                                JsonPropertyInfoValues<%s>(" fsharpType
            appendf "                                    IsProperty = true,"
            appendf "                                    IsPublic = true,"
            appendf "                                    DeclaringType = typeof<%s>," fqn
            appendf "                                    PropertyName = \"%s\"," field.Name
            appendf "                                    Getter = (fun (obj: obj) -> (obj :?> %s).%s)" fqn field.RawName
            appendf "                                )"
            appendf "                            )"

        appendf "                        |]"
        appendf "                    ),"
        appendf "                    SerializeHandler = (fun writer value ->"
        appendf "                    writer.WriteStartObject()"

        for field in fields do
            let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
            let call = writerCall field.Name field.RawName fsharpType
            append call

        appendf "                    writer.WriteEndObject()"
        appendf "                )"
        appendf "            )"
        appendf "        )"
        appendf "        if Serde.FS.Serde.Debug then"
        appendf "            printfn \"[SerdeDebug] Using generated converter for %%s\" typeof<%s>.FullName" fqn
        appendf "        info"

        sb.ToString()

    let emitOption (info: SerdeTypeInfo) : string =
        let inner =
            match info.Raw.Kind with
            | TypeModel.Option inner -> inner
            | _ -> failwith "emitOption called with non-Option kind"

        let pascalName = TypeModel.typeInfoToPascalName info.Raw
        let fqType = TypeModel.typeInfoToFqFSharpType info.Raw
        let innerFqType = TypeModel.typeInfoToFqFSharpType inner
        let converterName = pascalName + "Converter"
        let fnName = lowerFirst pascalName + "JsonTypeInfo"

        let sb = StringBuilder()
        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" pascalName
        append ""
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" pascalName
        append ""
        appendf "    type internal %s() =" converterName
        appendf "        inherit JsonConverter<%s>()" fqType
        appendf "        override _.Read(reader, _typeToConvert, options) ="
        appendf "            if reader.TokenType = JsonTokenType.Null then None"
        appendf "            else Some(JsonSerializer.Deserialize<%s>(&reader, options))" innerFqType
        appendf "        override _.Write(writer, value, options) ="
        appendf "            match value with"
        appendf "            | None -> writer.WriteNullValue()"
        appendf "            | Some v -> JsonSerializer.Serialize(writer, v, options)"
        append ""
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqType
        appendf "        JsonMetadataServices.CreateValueInfo<%s>(options, %s())" fqType converterName

        sb.ToString()

    let emitTuple (info: SerdeTypeInfo) : string =
        let elements =
            match info.Raw.Kind with
            | TypeModel.Tuple elems -> elems
            | _ -> failwith "emitTuple called with non-Tuple kind"

        let pascalName = TypeModel.typeInfoToPascalName info.Raw
        let fqType = TypeModel.typeInfoToFqFSharpType info.Raw
        let converterName = pascalName + "Converter"
        let fnName = lowerFirst pascalName + "JsonTypeInfo"

        let sb = StringBuilder()
        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" pascalName
        append ""
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" pascalName
        append ""
        appendf "    type internal %s() =" converterName
        appendf "        inherit JsonConverter<%s>()" fqType
        appendf "        override _.Read(reader, _typeToConvert, options) ="
        appendf "            if reader.TokenType <> JsonTokenType.StartArray then"
        appendf "                raise (JsonException(\"Expected StartArray for tuple\"))"
        for i, elem in elements |> List.mapi (fun i x -> i, x) do
            let elemFqType = TypeModel.typeInfoToFqFSharpType elem.Type
            appendf "            reader.Read() |> ignore"
            appendf "            let e%d = JsonSerializer.Deserialize<%s>(&reader, options)" i elemFqType
        appendf "            reader.Read() |> ignore"
        let tupleExpr = elements |> List.mapi (fun i _ -> sprintf "e%d" i) |> String.concat ", "
        appendf "            (%s)" tupleExpr
        appendf "        override _.Write(writer, value, options) ="
        appendf "            writer.WriteStartArray()"
        let destructure = elements |> List.mapi (fun i _ -> sprintf "e%d" i) |> String.concat ", "
        appendf "            let (%s) = value" destructure
        for i, elem in elements |> List.mapi (fun i x -> i, x) do
            let elemFqType = TypeModel.typeInfoToFqFSharpType elem.Type
            appendf "            JsonSerializer.Serialize(writer, e%d, options)" i
        appendf "            writer.WriteEndArray()"
        append ""
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqType
        appendf "        JsonMetadataServices.CreateValueInfo<%s>(options, %s())" fqType converterName

        sb.ToString()

    type private CaseShape = Nullary | SingleField | TupleFields | RecordFields

    let private classifyCaseShape (case: SerdeUnionCaseInfo) =
        match case.Fields with
        | [] -> Nullary
        | [_] -> SingleField
        | fields ->
            if fields |> List.forall (fun f -> f.RawName = "Item") then TupleFields
            else RecordFields

    let emitUnion (info: SerdeTypeInfo) : string =
        let cases = info.UnionCases |> Option.defaultValue []
        let fqn = fullyQualifiedName info
        let pascalName = info.Raw.TypeName
        let converterName = pascalName + "Converter"
        let fnName = lowerFirst pascalName + "JsonTypeInfo"

        let activeCases = cases |> List.filter (fun c -> not c.Attributes.Skip)
        let hasSkippedCases = cases |> List.exists (fun c -> c.Attributes.Skip)

        let sb = StringBuilder()
        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" pascalName
        append ""
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" pascalName
        append ""
        appendf "    type internal %s() =" converterName
        appendf "        inherit JsonConverter<%s>()" fqn

        // Read override
        appendf "        override _.Read(reader, _typeToConvert, options) ="
        appendf "            if reader.TokenType <> JsonTokenType.StartObject then"
        appendf "                raise (JsonException(\"Expected StartObject for union\"))"
        appendf "            reader.Read() |> ignore"
        appendf "            let caseName = reader.GetString()"
        appendf "            reader.Read() |> ignore"

        for i, case in activeCases |> List.mapi (fun i x -> i, x) do
            let keyword = if i = 0 then "if" else "elif"
            let shape = classifyCaseShape case
            appendf "            %s caseName = \"%s\" then" keyword case.CaseName
            match shape with
            | Nullary ->
                appendf "                if reader.TokenType <> JsonTokenType.Null then"
                appendf "                    raise (JsonException(\"Expected null for nullary union case\"))"
                appendf "                reader.Read() |> ignore"
                appendf "                %s.%s" fqn case.RawCaseName
            | SingleField ->
                let field = case.Fields.[0]
                let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
                appendf "                let v = JsonSerializer.Deserialize<%s>(&reader, options)" fsharpType
                appendf "                reader.Read() |> ignore"
                appendf "                %s.%s(v)" fqn case.RawCaseName
            | TupleFields ->
                appendf "                if reader.TokenType <> JsonTokenType.StartArray then"
                appendf "                    raise (JsonException(\"Expected StartArray for tuple union case\"))"
                for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                    let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
                    appendf "                reader.Read() |> ignore"
                    appendf "                let e%d = JsonSerializer.Deserialize<%s>(&reader, options)" j fsharpType
                appendf "                reader.Read() |> ignore"
                appendf "                reader.Read() |> ignore"
                let args = case.Fields |> List.mapi (fun j _ -> sprintf "e%d" j) |> String.concat ", "
                appendf "                %s.%s(%s)" fqn case.RawCaseName args
            | RecordFields ->
                appendf "                if reader.TokenType <> JsonTokenType.StartObject then"
                appendf "                    raise (JsonException(\"Expected StartObject for record union case\"))"
                appendf "                reader.Read() |> ignore"
                for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                    let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
                    appendf "                let mutable f%d = Unchecked.defaultof<%s>" j fsharpType
                appendf "                while reader.TokenType <> JsonTokenType.EndObject do"
                appendf "                    let propName = reader.GetString()"
                appendf "                    reader.Read() |> ignore"
                for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                    let kw = if j = 0 then "if" else "elif"
                    let fsharpType = TypeModel.typeInfoToFqFSharpType field.Type
                    appendf "                    %s propName = \"%s\" then" kw field.Name
                    appendf "                        f%d <- JsonSerializer.Deserialize<%s>(&reader, options)" j fsharpType
                appendf "                    else reader.Skip()"
                appendf "                    reader.Read() |> ignore"
                appendf "                reader.Read() |> ignore"
                let args = case.Fields |> List.mapi (fun j _ -> sprintf "f%d" j) |> String.concat ", "
                appendf "                %s.%s(%s)" fqn case.RawCaseName args

        appendf "            else raise (JsonException(sprintf \"Unknown union case: %%s\" caseName))"

        // Write override
        appendf "        override _.Write(writer, value, options) ="
        appendf "            writer.WriteStartObject()"
        appendf "            match value with"

        for case in activeCases do
            let shape = classifyCaseShape case
            match shape with
            | Nullary ->
                appendf "            | %s.%s ->" fqn case.RawCaseName
                appendf "                writer.WriteNull(\"%s\")" case.CaseName
            | SingleField ->
                appendf "            | %s.%s(v) ->" fqn case.RawCaseName
                appendf "                writer.WritePropertyName(\"%s\")" case.CaseName
                appendf "                JsonSerializer.Serialize(writer, v, options)"
            | TupleFields ->
                let args = case.Fields |> List.mapi (fun j _ -> sprintf "e%d" j) |> String.concat ", "
                appendf "            | %s.%s(%s) ->" fqn case.RawCaseName args
                appendf "                writer.WritePropertyName(\"%s\")" case.CaseName
                appendf "                writer.WriteStartArray()"
                for j in 0 .. case.Fields.Length - 1 do
                    appendf "                JsonSerializer.Serialize(writer, e%d, options)" j
                appendf "                writer.WriteEndArray()"
            | RecordFields ->
                let args = case.Fields |> List.mapi (fun j _ -> sprintf "e%d" j) |> String.concat ", "
                appendf "            | %s.%s(%s) ->" fqn case.RawCaseName args
                appendf "                writer.WritePropertyName(\"%s\")" case.CaseName
                appendf "                writer.WriteStartObject()"
                for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                    appendf "                writer.WritePropertyName(\"%s\")" field.Name
                    appendf "                JsonSerializer.Serialize(writer, e%d, options)" j
                appendf "                writer.WriteEndObject()"

        if hasSkippedCases then
            appendf "            | _ -> raise (JsonException(\"Unknown or skipped union case\"))"

        appendf "            writer.WriteEndObject()"

        append ""
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqn
        appendf "        JsonMetadataServices.CreateValueInfo<%s>(options, %s())" fqn converterName

        sb.ToString()

    let emitEnum (info: SerdeTypeInfo) : string =
        let cases = info.EnumCases |> Option.defaultValue []
        let fqn = fullyQualifiedName info
        let pascalName = info.Raw.TypeName
        let converterName = pascalName + "Converter"
        let fnName = lowerFirst pascalName + "JsonTypeInfo"

        let sb = StringBuilder()
        let append (s: string) = sb.AppendLine(s) |> ignore
        let appendf fmt = Printf.kprintf append fmt

        append "// <auto-generated />"
        appendf "module rec Serde.Generated.%s" pascalName
        append ""
        append "open System.Text.Json"
        append "open System.Text.Json.Serialization"
        append "open System.Text.Json.Serialization.Metadata"
        append ""
        appendf "[<AutoOpen>]"
        appendf "module internal %sSerdeTypeInfo =" pascalName
        append ""
        appendf "    type internal %s() =" converterName
        appendf "        inherit JsonConverter<%s>()" fqn
        appendf "        override _.Read(reader, _typeToConvert, _options) ="
        appendf "            let s = reader.GetString()"

        let activeCases = cases |> List.filter (fun c -> not c.Attributes.Skip)
        for i, c in activeCases |> List.mapi (fun i x -> i, x) do
            let keyword = if i = 0 then "if" else "elif"
            appendf "            %s s = \"%s\" then %s.%s" keyword c.CaseName fqn c.RawCaseName

        appendf "            else raise (JsonException(sprintf \"Unknown enum value: %%s\" s))"

        appendf "        override _.Write(writer, value, _options) ="

        for i, c in activeCases |> List.mapi (fun i x -> i, x) do
            let keyword = if i = 0 then "if" else "elif"
            appendf "            %s value = %s.%s then writer.WriteStringValue(\"%s\")" keyword fqn c.RawCaseName c.CaseName

        appendf "            else raise (JsonException(sprintf \"Unknown enum value: %%A\" value))"

        append ""
        appendf "    let %s (options: JsonSerializerOptions) : JsonTypeInfo<%s> =" fnName fqn
        appendf "        JsonMetadataServices.CreateValueInfo<%s>(options, %s())" fqn converterName

        sb.ToString()

    let emit (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeModel.Option _ -> emitOption info
        | TypeModel.Tuple _ -> emitTuple info
        | TypeModel.Enum _ -> emitEnum info
        | TypeModel.Union _ -> emitUnion info
        | _ -> emitRecord info

    let private resolverModuleName (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeModel.Option _ | TypeModel.Tuple _ -> TypeModel.typeInfoToPascalName info.Raw
        | _ -> info.Raw.TypeName

    let private resolverFqn (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeModel.Option _ | TypeModel.Tuple _ -> TypeModel.typeInfoToFqFSharpType info.Raw
        | _ -> fullyQualifiedName info

    let private resolverFnName (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | TypeModel.Option _ | TypeModel.Tuple _ -> lowerFirst (TypeModel.typeInfoToPascalName info.Raw) + "JsonTypeInfo"
        | _ -> lowerFirst info.Raw.TypeName + "JsonTypeInfo"

    let emitResolver (types: SerdeTypeInfo list) : string option =
        match types with
        | [] -> None
        | _ ->
            let sb = StringBuilder()
            let append (s: string) = sb.AppendLine(s) |> ignore
            let appendf fmt = Printf.kprintf append fmt

            append "// <auto-generated />"
            append "module Serde.Generated.SerdeStjResolver"
            append ""
            append "open System.Text.Json"
            append "open System.Text.Json.Serialization.Metadata"

            for info in types do
                appendf "open Serde.Generated.%s" (resolverModuleName info)

            append ""
            append "type internal SerdeStjGeneratedResolver() ="
            append "    interface IJsonTypeInfoResolver with"
            append "        member _.GetTypeInfo(ty, options) ="

            for i, info in types |> List.mapi (fun i x -> i, x) do
                let fqn = resolverFqn info
                let fnName = resolverFnName info
                let keyword = if i = 0 then "if" else "elif"
                appendf "            %s ty = typeof<%s> then %s options :> JsonTypeInfo" keyword fqn fnName

            append "            else null"
            append ""
            append "do Serde.FS.SystemTextJson.SerdeStjResolverRegistry.registerResolver(SerdeStjGeneratedResolver())"

            Some (sb.ToString())

type StjCodeEmitter() =
    interface ISerdeCodeEmitter with
        member _.Emit(info) = StjCodeEmitterImpl.emit info
    interface ISerdeResolverEmitter with
        member _.EmitResolver(types) = StjCodeEmitterImpl.emitResolver types
