namespace Serde.FS.Json.SourceGen

open System.Text
open Serde.FS
open FSharp.SourceDjinn.TypeModel

module internal JsonCodeEmitterImpl =

    let lowerFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToLowerInvariant(s.[0])) + s.Substring(1)

    let upperFirst (s: string) =
        if System.String.IsNullOrEmpty(s) then s
        else string (System.Char.ToUpperInvariant(s.[0])) + s.Substring(1)

    let sanitize (name: string) =
        name
            .Replace(".", "_")
            .Replace("+", "_")
            .Replace("`", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace("[", "_")
            .Replace("]", "_")

    let fullyQualifiedName (info: SerdeTypeInfo) : string =
        let parts =
            [ yield! info.Raw.Namespace |> Option.toList
              yield! info.Raw.EnclosingModules
              yield info.Raw.TypeName ]
        String.concat "." parts

    /// Pascal name that accounts for instantiated generics.
    let rec private pascalNameForArg (ti: Types.TypeInfo) : string =
        if not ti.GenericArguments.IsEmpty then
            let argPart = ti.GenericArguments |> List.map pascalNameForArg |> String.concat ""
            sanitize (upperFirst ti.TypeName) + argPart
        else
            sanitize (Types.typeInfoToPascalName ti)

    /// The name used for module/codec/function names.
    let emittedName (info: SerdeTypeInfo) : string =
        match info.GenericContext with
        | Some ctx ->
            let argNames = ctx.GenericArguments |> List.map pascalNameForArg |> String.concat ""
            sanitize $"%s{info.Raw.TypeName}_%s{argNames}"
        | None -> sanitize info.Raw.TypeName

    /// The fully-qualified F# type expression for typeof<>.
    let emittedFqn (info: SerdeTypeInfo) : string =
        match info.GenericContext with
        | Some ctx ->
            let baseParts =
                [ yield! info.Raw.Namespace |> Option.toList
                  yield! info.Raw.EnclosingModules
                  yield info.Raw.TypeName ]
            let baseName = String.concat "." baseParts
            let argNames = ctx.GenericArguments |> List.map Types.typeInfoToFqFSharpType |> String.concat ", "
            $"%s{baseName}<%s{argNames}>"
        | None -> fullyQualifiedName info

    /// Generates the encode expression for a single field value.
    let private encodeFieldExpr (fieldName: string) (rawFieldName: string) (fsharpType: string) (normalizedType: string) (isOption: bool) (innerType: string) (indent: string) : string =
        if isOption then
            let innerIndent = indent + "    "
            let encodeInner =
                $"%s{innerIndent}let fieldCodec = Serde.FS.Json.Codec.CodecResolver.resolve typeof<%s{innerType}> Serde.FS.Json.Codec.GlobalCodecRegistry.Current\n" +
                $"%s{innerIndent}(\"%s{fieldName}\", fieldCodec.Encode(box v))"
            $"%s{indent}match value.%s{rawFieldName} with\n" +
            $"%s{indent}| Some v ->\n%s{encodeInner}\n" +
            $"%s{indent}| None ->\n" +
            $"%s{innerIndent}(\"%s{fieldName}\", Serde.FS.Json.Codec.JsonValue.Null)"
        else
            $"%s{indent}let fieldCodec_%s{rawFieldName} = Serde.FS.Json.Codec.CodecResolver.resolve typeof<%s{fsharpType}> Serde.FS.Json.Codec.GlobalCodecRegistry.Current\n" +
            $"%s{indent}(\"%s{fieldName}\", fieldCodec_%s{rawFieldName}.Encode(box value.%s{rawFieldName}))"

    /// Determines if a type is an option and extracts the inner type.
    let private parseOptionType (fsharpType: string) =
        let normalizedType = fsharpType.Trim().ToLowerInvariant()
        if normalizedType.EndsWith(" option") then
            true, fsharpType.Trim().Substring(0, fsharpType.Trim().Length - " option".Length).Trim()
        elif normalizedType.StartsWith("option<") && normalizedType.EndsWith(">") then
            true, fsharpType.Trim().Substring("option<".Length, fsharpType.Trim().Length - "option<".Length - 1).Trim()
        else
            false, fsharpType.Trim()

    let emitRecord (info: SerdeTypeInfo) : string =
        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        let fields = info.Fields |> Option.defaultValue []
        let name = emittedName info

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{name}"
        append ""
        append "open System"
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{name}SerdeCodec ="
        append ""

        let fnName = lowerFirst name + "JsonCodec"
        let fqn = emittedFqn info

        append $"    let %s{fnName} : IJsonCodec<%s{fqn}> ="
        append $"        {{ new IJsonCodec<%s{fqn}> with"

        // Encode
        append "            member _.Encode(value) ="
        append "                JsonValue.Object ["
        for field in fields do
            let fsharpType = Types.typeInfoToFqFSharpType field.Type
            let isOption, innerType = parseOptionType fsharpType
            let normalizedType = fsharpType.Trim().ToLowerInvariant()
            let indent = "                    "
            let expr = encodeFieldExpr field.Name field.RawName fsharpType normalizedType isOption innerType indent
            append expr
        append "                ]"

        // Decode
        append "            member _.Decode(json) ="
        append "                match json with"
        append "                | JsonValue.Object fields ->"
        append "                    let fieldMap = dict fields"

        for field in fields do
            let fsharpType = Types.typeInfoToFqFSharpType field.Type
            let isOption, innerType = parseOptionType fsharpType
            if isOption then
                append $"                    let %s{lowerFirst field.RawName} ="
                append $"                        match fieldMap.TryGetValue(\"%s{field.Name}\") with"
                append $"                        | true, JsonValue.Null -> None"
                append $"                        | true, v ->"
                append $"                            let fieldCodec = CodecResolver.resolve typeof<%s{innerType}> GlobalCodecRegistry.Current"
                append $"                            Some(fieldCodec.Decode(v) :?> %s{innerType})"
                append $"                        | false, _ -> None"
            else
                append $"                    let fieldCodec_%s{field.RawName} = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                append $"                    let %s{lowerFirst field.RawName} = fieldCodec_%s{field.RawName}.Decode(fieldMap.[\"%s{field.Name}\"]) :?> %s{fsharpType}"

        let fieldAssignments =
            fields
            |> List.map (fun f -> $"%s{f.RawName} = %s{lowerFirst f.RawName}")
            |> String.concat "; "
        append $"                    {{ %s{fieldAssignments} }} : %s{fqn}"
        append "                | _ -> failwith \"Expected JSON object\""
        append "        }"

        // Field-level codec overrides (register in GlobalCodecRegistry)
        let fieldsWithCodecs = fields |> List.indexed |> List.filter (fun (_, f) -> f.CodecType.IsSome)
        if not fieldsWithCodecs.IsEmpty then
            append ""
            append "    // Field-level codec registrations"
            for (_i, field) in fieldsWithCodecs do
                let codecFqn = field.CodecType.Value
                let fsharpType = Types.typeInfoToFqFSharpType field.Type
                append $"    let private _fieldCodecReg_%s{field.RawName} ="
                append $"        let codec = %s{codecFqn}() :> IJsonCodec<%s{fsharpType}>"
                append $"        GlobalCodecRegistry.Current <- CodecRegistry.add (typeof<%s{fsharpType}>, JsonCodec.boxCodec codec) GlobalCodecRegistry.Current"

        sb.ToString()

    let emitOption (info: SerdeTypeInfo) : string =
        let inner =
            match info.Raw.Kind with
            | Types.Option inner -> inner
            | _ -> failwith "emitOption called with non-Option kind"

        let pascalName = Types.typeInfoToPascalName info.Raw
        let fqType = Types.typeInfoToFqFSharpType info.Raw
        let innerFqType = Types.typeInfoToFqFSharpType inner
        let fnName = lowerFirst pascalName + "JsonCodec"

        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{pascalName}"
        append ""
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{pascalName}SerdeCodec ="
        append ""
        append $"    let %s{fnName} : IJsonCodec<%s{fqType}> ="
        append $"        {{ new IJsonCodec<%s{fqType}> with"
        append "            member _.Encode(value) ="
        append "                match value with"
        append "                | None -> JsonValue.Null"
        append "                | Some v ->"
        append $"                    let innerCodec = CodecResolver.resolve typeof<%s{innerFqType}> GlobalCodecRegistry.Current"
        append "                    innerCodec.Encode(box v)"
        append "            member _.Decode(json) ="
        append "                match json with"
        append "                | JsonValue.Null -> None"
        append "                | v ->"
        append $"                    let innerCodec = CodecResolver.resolve typeof<%s{innerFqType}> GlobalCodecRegistry.Current"
        append $"                    Some(innerCodec.Decode(v) :?> %s{innerFqType})"
        append "        }"

        sb.ToString()

    let emitTuple (info: SerdeTypeInfo) : string =
        let elements =
            match info.Raw.Kind with
            | Types.Tuple elems -> elems
            | _ -> failwith "emitTuple called with non-Tuple kind"

        let pascalName = Types.typeInfoToPascalName info.Raw
        let fqType = Types.typeInfoToFqFSharpType info.Raw
        let fnName = lowerFirst pascalName + "JsonCodec"

        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{pascalName}"
        append ""
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{pascalName}SerdeCodec ="
        append ""
        append $"    let %s{fnName} : IJsonCodec<%s{fqType}> ="
        append $"        {{ new IJsonCodec<%s{fqType}> with"
        append "            member _.Encode(value) ="
        let destructure = elements |> List.mapi (fun i _ -> $"e%d{i}") |> String.concat ", "
        append $"                let (%s{destructure}) = value"
        append "                JsonValue.Array ["
        for i, elem in elements |> List.mapi (fun i x -> i, x) do
            let elemFqType = Types.typeInfoToFqFSharpType elem.Type
            append $"                    let elemCodec_%d{i} = CodecResolver.resolve typeof<%s{elemFqType}> GlobalCodecRegistry.Current"
            append $"                    elemCodec_%d{i}.Encode(box e%d{i})"
        append "                ]"
        append "            member _.Decode(json) ="
        append "                match json with"
        append "                | JsonValue.Array items ->"
        for i, elem in elements |> List.mapi (fun i x -> i, x) do
            let elemFqType = Types.typeInfoToFqFSharpType elem.Type
            append $"                    let elemCodec_%d{i} = CodecResolver.resolve typeof<%s{elemFqType}> GlobalCodecRegistry.Current"
            append $"                    let e%d{i} = elemCodec_%d{i}.Decode(items.[%d{i}]) :?> %s{elemFqType}"
        let tupleExpr = elements |> List.mapi (fun i _ -> $"e%d{i}") |> String.concat ", "
        append $"                    (%s{tupleExpr})"
        append "                | _ -> failwith \"Expected JSON array for tuple\""
        append "        }"

        sb.ToString()

    type private CaseShape = Nullary | SingleField | TupleFields | RecordFields

    let private classifyCaseShape (case: SerdeUnionCaseInfo) =
        match case.Fields with
        | [] -> Nullary
        | [_] -> SingleField
        | fields ->
            if fields |> List.forall (fun f -> f.RawName = "Item") then TupleFields
            else RecordFields

    type private UnionKind = WrapperUnion | MultiCaseUnion

    let private classifyUnionKind (cases: SerdeUnionCaseInfo list) =
        match cases with
        | [single] when single.Fields.Length = 1 -> WrapperUnion
        | _ -> MultiCaseUnion

    let emitUnion (info: SerdeTypeInfo) : string =
        let cases = info.UnionCases |> Option.defaultValue []
        let fqn = emittedFqn info
        let caseFqn =
            match info.GenericContext with
            | Some _ ->
                let parts =
                    [ yield! info.Raw.Namespace |> Option.toList
                      yield! info.Raw.EnclosingModules ]
                if parts.IsEmpty then info.Raw.TypeName
                else String.concat "." parts
            | None -> fullyQualifiedName info
        let pascalName = emittedName info
        let fnName = lowerFirst pascalName + "JsonCodec"

        let activeCases = cases |> List.filter (fun c -> not c.Attributes.Skip)
        let hasSkippedCases = cases |> List.exists (fun c -> c.Attributes.Skip)
        let kind = classifyUnionKind cases

        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{pascalName}"
        append ""
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{pascalName}SerdeCodec ="
        append ""
        append $"    let %s{fnName} : IJsonCodec<%s{fqn}> ="
        append $"        {{ new IJsonCodec<%s{fqn}> with"

        match kind with
        | WrapperUnion ->
            let case = activeCases.[0]
            let field = case.Fields.[0]
            let fsharpType = Types.typeInfoToFqFSharpType field.Type

            // Encode
            append "            member _.Encode(value) ="
            append "                match value with"
            append $"                | %s{caseFqn}.%s{case.RawCaseName}(v) ->"
            append $"                    let innerCodec = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
            append $"                    JsonValue.Object [\"%s{case.CaseName}\", innerCodec.Encode(box v)]"

            // Decode
            append "            member _.Decode(json) ="
            append "                match json with"
            append "                | JsonValue.Object [(caseName, payload)] ->"
            append $"                    if caseName = \"%s{case.CaseName}\" then"
            append $"                        let innerCodec = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
            append $"                        %s{caseFqn}.%s{case.RawCaseName}(innerCodec.Decode(payload) :?> %s{fsharpType})"
            append "                    else failwith (sprintf \"Unknown union case: %s\" caseName)"
            append "                | _ -> failwith \"Expected JSON object for wrapper union\""

        | MultiCaseUnion ->
            // Encode
            append "            member _.Encode(value) ="
            append "                match value with"

            for case in activeCases do
                let shape = classifyCaseShape case
                match shape with
                | Nullary ->
                    append $"                | %s{caseFqn}.%s{case.RawCaseName} ->"
                    append $"                    JsonValue.Object [\"Case\", JsonValue.String \"%s{case.CaseName}\"; \"Fields\", JsonValue.Array []]"
                | SingleField ->
                    let field = case.Fields.[0]
                    let fsharpType = Types.typeInfoToFqFSharpType field.Type
                    append $"                | %s{caseFqn}.%s{case.RawCaseName}(v) ->"
                    append $"                    let fieldCodec = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                    append $"                    JsonValue.Object [\"Case\", JsonValue.String \"%s{case.CaseName}\"; \"Fields\", JsonValue.Array [fieldCodec.Encode(box v)]]"
                | TupleFields ->
                    let args = case.Fields |> List.mapi (fun j _ -> $"e%d{j}") |> String.concat ", "
                    append $"                | %s{caseFqn}.%s{case.RawCaseName}(%s{args}) ->"
                    append "                    let fieldValues = ["
                    for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                        let fsharpType = Types.typeInfoToFqFSharpType field.Type
                        append $"                        let fc_%d{j} = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                        append $"                        fc_%d{j}.Encode(box e%d{j})"
                    append "                    ]"
                    append $"                    JsonValue.Object [\"Case\", JsonValue.String \"%s{case.CaseName}\"; \"Fields\", JsonValue.Array fieldValues]"
                | RecordFields ->
                    let args = case.Fields |> List.mapi (fun j _ -> $"e%d{j}") |> String.concat ", "
                    append $"                | %s{caseFqn}.%s{case.RawCaseName}(%s{args}) ->"
                    append "                    let fieldValues = ["
                    for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                        let fsharpType = Types.typeInfoToFqFSharpType field.Type
                        append $"                        let fc_%d{j} = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                        append $"                        fc_%d{j}.Encode(box e%d{j})"
                    append "                    ]"
                    append $"                    JsonValue.Object [\"Case\", JsonValue.String \"%s{case.CaseName}\"; \"Fields\", JsonValue.Array fieldValues]"

            if hasSkippedCases then
                append "                | _ -> failwith \"Unknown or skipped union case\""

            // Decode
            append "            member _.Decode(json) ="
            append "                match json with"
            append "                | JsonValue.Object fields ->"
            append "                    let fieldMap = dict fields"
            append "                    let caseName ="
            append "                        match fieldMap.[\"Case\"] with"
            append "                        | JsonValue.String s -> s"
            append "                        | _ -> failwith \"Expected string for 'Case'\""
            append "                    let fieldsArr ="
            append "                        match fieldMap.[\"Fields\"] with"
            append "                        | JsonValue.Array items -> items"
            append "                        | _ -> failwith \"Expected array for 'Fields'\""

            for i, case in activeCases |> List.mapi (fun i x -> i, x) do
                let keyword = if i = 0 then "if" else "elif"
                let shape = classifyCaseShape case
                append $"                    %s{keyword} caseName = \"%s{case.CaseName}\" then"
                match shape with
                | Nullary ->
                    append $"                        %s{caseFqn}.%s{case.RawCaseName}"
                | SingleField ->
                    let field = case.Fields.[0]
                    let fsharpType = Types.typeInfoToFqFSharpType field.Type
                    append $"                        let fc = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                    append $"                        %s{caseFqn}.%s{case.RawCaseName}(fc.Decode(fieldsArr.[0]) :?> %s{fsharpType})"
                | TupleFields ->
                    for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                        let fsharpType = Types.typeInfoToFqFSharpType field.Type
                        append $"                        let fc_%d{j} = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                        append $"                        let e%d{j} = fc_%d{j}.Decode(fieldsArr.[%d{j}]) :?> %s{fsharpType}"
                    let args = case.Fields |> List.mapi (fun j _ -> $"e%d{j}") |> String.concat ", "
                    append $"                        %s{caseFqn}.%s{case.RawCaseName}(%s{args})"
                | RecordFields ->
                    for j, field in case.Fields |> List.mapi (fun j x -> j, x) do
                        let fsharpType = Types.typeInfoToFqFSharpType field.Type
                        append $"                        let fc_%d{j} = CodecResolver.resolve typeof<%s{fsharpType}> GlobalCodecRegistry.Current"
                        append $"                        let e%d{j} = fc_%d{j}.Decode(fieldsArr.[%d{j}]) :?> %s{fsharpType}"
                    let args = case.Fields |> List.mapi (fun j _ -> $"e%d{j}") |> String.concat ", "
                    append $"                        %s{caseFqn}.%s{case.RawCaseName}(%s{args})"

            append "                    else failwith (sprintf \"Unknown union case: %s\" caseName)"
            append "                | _ -> failwith \"Expected JSON object for union\""

        append "        }"

        sb.ToString()

    let emitEnum (info: SerdeTypeInfo) : string =
        let cases = info.EnumCases |> Option.defaultValue []
        let fqn = emittedFqn info
        let pascalName = emittedName info
        let fnName = lowerFirst pascalName + "JsonCodec"

        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        let activeCases = cases |> List.filter (fun c -> not c.Attributes.Skip)

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{pascalName}"
        append ""
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{pascalName}SerdeCodec ="
        append ""
        append $"    let %s{fnName} : IJsonCodec<%s{fqn}> ="
        append $"        {{ new IJsonCodec<%s{fqn}> with"

        // Encode
        append "            member _.Encode(value) ="
        for i, c in activeCases |> List.mapi (fun i x -> i, x) do
            let keyword = if i = 0 then "if" else "elif"
            append $"                %s{keyword} value = %s{fqn}.%s{c.RawCaseName} then JsonValue.String \"%s{c.CaseName}\""
        append "                else failwith (sprintf \"Unknown enum value: %A\" value)"

        // Decode
        append "            member _.Decode(json) ="
        append "                match json with"
        append "                | JsonValue.String s ->"
        for i, c in activeCases |> List.mapi (fun i x -> i, x) do
            let keyword = if i = 0 then "if" else "elif"
            append $"                    %s{keyword} s = \"%s{c.CaseName}\" then %s{fqn}.%s{c.RawCaseName}"
        append "                    else failwith (sprintf \"Unknown enum value: %s\" s)"
        append "                | _ -> failwith \"Expected JSON string for enum\""
        append "        }"

        sb.ToString()

    let emitCodec (info: SerdeTypeInfo) (codecFqn: string) : string =
        let fqn = emittedFqn info
        let pascalName = emittedName info
        let fnName = lowerFirst pascalName + "JsonCodec"

        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{pascalName}"
        append ""
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{pascalName}SerdeCodec ="
        append ""
        append $"    let %s{fnName} : IJsonCodec<%s{fqn}> ="
        append $"        %s{codecFqn}() :> IJsonCodec<%s{fqn}>"

        sb.ToString()

    /// Detects a generic single-case single-field DU definition (e.g. Wrapper<'T> = Wrapper of 'T).
    let internal isGenericSingleCaseWrapper (info: SerdeTypeInfo) =
        info.Raw.IsGenericDefinition
        && match info.UnionCases with
           | Some [case] when case.Fields.Length = 1 -> true
           | _ -> false

    let emitGenericWrapperFactory (info: SerdeTypeInfo) : string =
        let name = sanitize info.Raw.TypeName
        let fqn = fullyQualifiedName info
        let arity = info.Raw.GenericParameters.Length
        let wildcards = List.replicate arity "_" |> String.concat ", "
        let factoryFnName = lowerFirst name + "CodecFactory"

        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        append "// <auto-generated />"
        append $"module rec Serde.Generated.%s{name}"
        append ""
        append "open System"
        append "open Serde.FS.Json.Codec"
        append ""
        append "[<AutoOpen>]"
        append $"module internal %s{name}SerdeCodecFactory ="
        append ""
        append $"    let %s{factoryFnName} (typeArgs: Type[]) (registry: CodecRegistry) : IJsonCodec ="
        append "        let innerType = typeArgs.[0]"
        append "        let innerCodec = CodecResolver.resolve innerType registry"
        append $"        let wrapperType = typedefof<%s{fqn}<%s{wildcards}>>.MakeGenericType(typeArgs)"
        append "        let caseInfo = Microsoft.FSharp.Reflection.FSharpType.GetUnionCases(wrapperType).[0]"
        append "        { new IJsonCodec with"
        append "            member _.Type = wrapperType"
        append "            member _.Encode obj ="
        append "                let fields = Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields(obj, wrapperType) |> snd"
        append "                innerCodec.Encode(fields.[0])"
        append "            member _.Decode json ="
        append "                let inner = innerCodec.Decode(json)"
        append "                Microsoft.FSharp.Reflection.FSharpValue.MakeUnion(caseInfo, [| inner |])"
        append "        }"

        sb.ToString()

    let emit (info: SerdeTypeInfo) : string =
        if isGenericSingleCaseWrapper info then
            emitGenericWrapperFactory info
        else
            match info.CodecType with
            | Some codecFqn -> emitCodec info codecFqn
            | None ->
                match info.Raw.Kind with
                | Types.Option _ -> emitOption info
                | Types.Tuple _ -> emitTuple info
                | Types.Enum _ -> emitEnum info
                | Types.Union _ -> emitUnion info
                | _ -> emitRecord info

    let private resolverModuleName (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | Types.Option _ | Types.Tuple _ -> Types.typeInfoToPascalName info.Raw
        | _ -> emittedName info

    let private resolverFqn (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | Types.Option _ | Types.Tuple _ -> Types.typeInfoToFqFSharpType info.Raw
        | _ -> emittedFqn info

    let private resolverFnName (info: SerdeTypeInfo) : string =
        match info.Raw.Kind with
        | Types.Option _ | Types.Tuple _ -> lowerFirst (Types.typeInfoToPascalName info.Raw) + "JsonCodec"
        | _ -> lowerFirst (emittedName info) + "JsonCodec"

    /// Extracts the codec let-binding from a full emit output, stripping the module wrapper.
    /// Also makes the top-level binding private and removes field-level codec registration side-effects.
    let private extractCodecBody (fullEmit: string) : string =
        let lines = fullEmit.TrimEnd().Split([| '\n' |])
        let startIdx =
            lines |> Array.findIndex (fun l -> l.StartsWith("    let "))
        // Stop before field-level codec registrations if present
        let endIdx =
            match lines |> Array.tryFindIndex (fun l -> l.Contains("// Field-level codec registrations")) with
            | Some fieldStart -> fieldStart - 1
            | None -> lines.Length - 1
        let mutable lastLine = endIdx
        while lastLine > startIdx && System.String.IsNullOrWhiteSpace(lines.[lastLine]) do
            lastLine <- lastLine - 1
        let bodyLines = Array.copy lines.[startIdx..lastLine]
        // Make the top-level let binding private
        bodyLines.[0] <- bodyLines.[0].Replace("    let ", "    let private ")
        String.concat "\n" bodyLines

    /// Collects (fieldType, codecFqn) pairs for fields that have explicit Codec attributes.
    let private collectFieldLevelCodecs (types: SerdeTypeInfo list) : (string * string) list =
        [ for info in types do
            match info.Fields with
            | Some fields ->
                for field in fields do
                    match field.CodecType with
                    | Some codecFqn ->
                        let fsharpType = Types.typeInfoToFqFSharpType field.Type
                        yield (fsharpType, codecFqn)
                    | None -> ()
            | None -> () ]
        |> List.distinct

    /// Emits the consolidated ~SerdeJsonCodecs.json.g.fs file containing all codecs,
    /// a pure register function, and the registration side-effect.
    let emitConsolidatedFile (types: SerdeTypeInfo list) : string option =
        match types with
        | [] -> None
        | _ ->
            let sb = StringBuilder()
            let append (s: string) = sb.Append(s).Append('\n') |> ignore

            append "// <auto-generated />"
            append "namespace Serde.Generated"
            append ""
            append "open System"
            append "open Serde.FS.Json"
            append "open Serde.FS.Json.Codec"
            append ""
            append "[<AutoOpen>]"
            append "module SerdeJsonCodecs ="
            append ""

            // Emit all codec bodies inline
            for info in types do
                let fullCode = emit info
                let body = extractCodecBody fullCode
                append body
                append ""

            // Emit field-level codec bindings
            let fieldCodecs = collectFieldLevelCodecs types
            for (fsharpType, codecFqn) in fieldCodecs do
                let safeName = sanitize fsharpType |> lowerFirst
                append $"    let private _fieldCodec_%s{safeName} : IJsonCodec<%s{fsharpType}> = %s{codecFqn}() :> IJsonCodec<%s{fsharpType}>"
                append ""

            // Emit the pure register function (internal so Bootstrap class can access it)
            append "    let internal register (reg: CodecRegistry) : CodecRegistry ="
            append "        reg"

            // Register field-level codecs first (they may be needed by type codecs)
            for (fsharpType, _codecFqn) in fieldCodecs do
                let safeName = sanitize fsharpType |> lowerFirst
                append $"        |> CodecRegistry.add (typeof<%s{fsharpType}>, JsonCodec.boxCodec _fieldCodec_%s{safeName})"

            // Register type codecs
            for info in types do
                if isGenericSingleCaseWrapper info then
                    let fqn = fullyQualifiedName info
                    let arity = info.Raw.GenericParameters.Length
                    let wildcards = List.replicate arity "_" |> String.concat ", "
                    let factoryFnName = lowerFirst (sanitize info.Raw.TypeName) + "CodecFactory"
                    append $"        |> CodecRegistry.addFactory (typedefof<%s{fqn}<%s{wildcards}>>, %s{factoryFnName})"
                else
                    let fqn = resolverFqn info
                    let fnName = resolverFnName info
                    append $"        |> CodecRegistry.add (typeof<%s{fqn}>, JsonCodec.boxCodec %s{fnName})"
            append ""

            // Emit the IEntryPointBootstrap implementation so that the entry point
            // can discover and call Init() before the user's entry point runs.
            append "namespace Serde.Generated"
            append ""
            append "type JsonBootstrap() ="
            append "    interface Serde.FS.IEntryPointBootstrap with"
            append "        member _.Init () ="
            append "            Serde.Generated.SerdeJsonCodecs.register"
            append "            |> Serde.FS.Json.SerdeJson.registerCodecs"

            Some (sb.ToString())

module internal RpcDispatchEmitter =
    open System.Text
    open Serde.FS.SourceGen

    let private computeRoot (iface: RpcInterfaceInfo) =
        match iface.Root with
        | Some r when r.Length > 0 -> r
        | _ -> iface.ShortName

    let private computeVersionSegment (iface: RpcInterfaceInfo) =
        match iface.Version with
        | Some v when v.Length > 0 -> $"/%s{v}"
        | _ -> ""

    let emit (iface: RpcInterfaceInfo) : string =
        let sb = StringBuilder()
        let append (s: string) = sb.Append(s).Append('\n') |> ignore

        let root = computeRoot iface
        let versionSegment = computeVersionSegment iface
        let basePath = $"/rpc/%s{root}%s{versionSegment}"

        append "// <auto-generated />"
        append "namespace SerdeGenerated.Rpc"
        append ""
        append "open System"
        append "open System.Net.Http"
        append "open System.Text"
        append "open System.Threading.Tasks"
        append "open Serde.FS.Json"
        append ""

        // ── Routing module ──────────────────────────────────────────
        append $"module internal %s{iface.ShortName}_Routing ="
        append $"    let basePath = \"%s{basePath}\""
        append $"    let urlCaseValue = %d{iface.UrlCaseValue}"
        append ""
        append "    let applyUrlCase (methodName: string) ="
        append "        if urlCaseValue = 1 then"
        append "            let chars ="
        append "                methodName"
        append "                |> Seq.collect (fun c ->"
        append "                    if Char.IsUpper c then seq { '-'; Char.ToLowerInvariant c }"
        append "                    else seq { c })"
        append "                |> Seq.toArray"
        append "            let s = String(chars)"
        append "            if s.StartsWith(\"-\") then s.Substring(1) else s"
        append "        else methodName"
        append ""
        append "    let getFullUrl (baseUrl: string) (methodName: string) ="
        append "        let methodSegment = applyUrlCase methodName"
        append "        baseUrl.TrimEnd('/') + basePath + \"/\" + methodSegment"
        append ""

        // ── Server dispatch module ──────────────────────────────────
        append $"module %s{iface.ShortName} ="
        append ""

        // methods
        let methodList =
            iface.Methods
            |> List.map (fun m -> $"\"%s{m.MethodName}\"")
            |> String.concat "; "
        append $"    let methods : string list = [ %s{methodList} ]"
        append ""

        // deserializeDynamic
        append "    let deserializeDynamic (methodName: string) (json: string) : obj ="
        append "        match methodName with"
        for m in iface.Methods do
            append $"        | \"%s{m.MethodName}\" -> SerdeJson.deserialize<%s{m.InputType}>(json) :> obj"
        append "        | _ -> failwith (sprintf \"Unknown RPC method: %s\" methodName)"
        append ""

        // serializeDynamic
        append "    let serializeDynamic (methodName: string) (value: obj) : string ="
        append "        match methodName with"
        for m in iface.Methods do
            append $"        | \"%s{m.MethodName}\" -> SerdeJson.serialize<%s{m.OutputType}>(value :?> %s{m.OutputType})"
        append "        | _ -> failwith (sprintf \"Unknown RPC method: %s\" methodName)"
        append ""

        // invoke
        append "    let invoke (impl: obj) (methodName: string) (input: obj) : Task<obj> ="
        append $"        let api = impl :?> %s{iface.FullName}"
        append "        match methodName with"
        for m in iface.Methods do
            if m.InputType = "unit" then
                append $"        | \"%s{m.MethodName}\" ->"
                append "            task {"
                append $"                let! result = api.%s{m.MethodName}() |> Async.StartAsTask"
                append "                return result :> obj"
                append "            }"
            else
                append $"        | \"%s{m.MethodName}\" ->"
                append $"            let arg = input :?> %s{m.InputType}"
                append "            task {"
                append $"                let! result = api.%s{m.MethodName} arg |> Async.StartAsTask"
                append "                return result :> obj"
                append "            }"
        append "        | _ -> failwith (sprintf \"Unknown RPC method: %s\" methodName)"
        append ""

        // ── Client proxy ────────────────────────────────────────────
        // Implements the interface (Async<T>) and also exposes Task<T> members for .NET consumers.
        append $"type %s{iface.ShortName}Client(baseUrl: string, http: HttpClient) ="
        // Task-returning members (primary API for .NET consumers)
        for m in iface.Methods do
            if m.InputType = "unit" then
                append $"    member _.%s{m.MethodName}() : Task<%s{m.OutputType}> ="
                append $"        let url = %s{iface.ShortName}_Routing.getFullUrl baseUrl \"%s{m.MethodName}\""
                append "        task {"
                append "            use content = new StringContent(\"null\", Encoding.UTF8, \"application/json\")"
                append "            let! resp = http.PostAsync(url, content)"
                append "            resp.EnsureSuccessStatusCode() |> ignore"
                append "            let! respJson = resp.Content.ReadAsStringAsync()"
                append $"            return SerdeJson.deserialize<%s{m.OutputType}>(respJson)"
                append "        }"
            else
                append $"    member _.%s{m.MethodName}(arg: %s{m.InputType}) : Task<%s{m.OutputType}> ="
                append $"        let url = %s{iface.ShortName}_Routing.getFullUrl baseUrl \"%s{m.MethodName}\""
                append $"        let bodyJson = SerdeJson.serialize<%s{m.InputType}>(arg)"
                append "        task {"
                append "            use content = new StringContent(bodyJson, Encoding.UTF8, \"application/json\")"
                append "            let! resp = http.PostAsync(url, content)"
                append "            resp.EnsureSuccessStatusCode() |> ignore"
                append "            let! respJson = resp.Content.ReadAsStringAsync()"
                append $"            return SerdeJson.deserialize<%s{m.OutputType}>(respJson)"
                append "        }"
        // Interface implementation (wraps Task methods as Async)
        append $"    interface %s{iface.FullName} with"
        for m in iface.Methods do
            if m.InputType = "unit" then
                append $"        member this.%s{m.MethodName}() ="
                append $"            this.%s{m.MethodName}() |> Async.AwaitTask"
            else
                append $"        member this.%s{m.MethodName}(arg) ="
                append $"            this.%s{m.MethodName}(arg) |> Async.AwaitTask"
        append ""

        // ── Client factory + registration ───────────────────────────
        append $"module internal %s{iface.ShortName}_ClientFactory ="
        append "    let create (baseUrl: string) (http: HttpClient) : obj ="
        append $"        %s{iface.ShortName}Client(baseUrl, http) :> obj"
        append ""

        // Bootstrap class to register the client factory at startup
        append $"type %s{iface.ShortName}RpcBootstrap() ="
        append "    interface Serde.FS.IEntryPointBootstrap with"
        append "        member _.Init () ="
        append $"            Serde.FS.Json.RpcClient.register<%s{iface.FullName}>(%s{iface.ShortName}_ClientFactory.create)"

        sb.ToString()

type JsonCodeEmitter() =
    interface ISerdeCodeEmitter with
        member _.Emit(info) = JsonCodeEmitterImpl.emit info
        member _.HintNameSuffix = "json"
    interface ISerdeResolverEmitter with
        member _.EmitResolver(types) = JsonCodeEmitterImpl.emitConsolidatedFile types
        member _.ResolverHintName = "~SerdeJsonCodecs.json.g.fs"
        member _.EmitRegistrationFiles() = []
        member _.EmitPerTypeFiles = false
    interface ISerdeRpcEmitter with
        member _.EmitRpcModules(interfaces) =
            interfaces
            |> List.map (fun iface ->
                let hintName = $"~Rpc.%s{iface.ShortName}.json.g.fs"
                let code = RpcDispatchEmitter.emit iface
                (hintName, code))
